### ISSUE TITLE
usage with canvas/webgl?

### ISSUE THREAD

**Issue by dakom** [WebReflection/hyperHTML#103]
I'm thinking of switching from React to just a pure vDom implementation... but for my test project, I have a couple nodes that override componentDidMount, componentDidUpdate, and shouldComponentUpdate

Specifically - those components draw things via canvas and webgl, so they need to use inline logic to not replace the `<canvas>` element and rather store a reference to its context to draw to

Can this be done with hyperHTML? If so, how? :)

Thanks!

**Comment by WebReflection** [comment]
> switching from React to just a pure vDom implementation

just to start clear, there is **no vdom** in _hyperHTML_

> they need to use inline logic to not replace the <canvas> element and rather store a reference to its context to draw to

can you provide a basic example of what you need?

> Can this be done with hyperHTML?

absolutely. You can wire any logic/data/object once and be sure that's reused forever, including the canvas context associated with it

> If so, how? :)

if you could provide a basic example of what you need/want I can do a better job at providing an example on how to

**Comment by WebReflection** [comment]
P.S. this is a question. It's not a bug. Next time please use StackOverflow and its hyperhtml tag to that everyone can benefit from answers.

**Comment by dakom** [comment]
Thanks, will close this as an issue - if I have any further questions I'll be sure to post on SO
