### ISSUE TITLE
Parameter in render() of hyperHTML.component

### ISSUE THREAD

**Issue by kidwm** [WebReflection/hyperHTML#104]
Pass state like in react, see [react-future](https://github.com/reactjs/react-future/blob/master/09%20-%20Reduce%20State/01%20-%20Declarative%20Component%20Module.js):
```js
class Clock extends hyper.Component {
  get defaultState() { return {date: new Date()}; }
  render(state) {
    return this.html`
      <div>
        <h1>Hello, world!</h1>
        <h2>It is ${state.date.toLocaleTimeString()}.</h2>
      </div>`;
  }
}
```
Or any other better use case?

**Comment by WebReflection** [comment]
Use 'this.state' instead. The render is a public method and components are usable outside hyperHTML too. State belongs to the instance, not to who invokes the render. Moreover, if you invoke the render you can pass whatever you want keeping this.state accessible.

**Comment by WebReflection** [comment]
P.S. if you really want to have a `state` parameter, you can always define your render function as such:
```js
class Clock extends hyper.Component {
  get defaultState() { return {date: new Date()}; }
  render(state = this.state) {
    return this.html`
      <div>
        <h1>Hello, world!</h1>
        <h2>It is ${state.date.toLocaleTimeString()}.</h2>
      </div>`;
  }
}
```

**Comment by kidwm** [comment]
Got it, thanks for you explanation.
