### ISSUE TITLE
Recommendation for a router to compliment HyperHTML?

### ISSUE THREAD

**Issue by rchrdnsh** [WebReflection/hyperHTML#105]
I really like the concepts behind HyperHTML, but I realize that it's not a full web app solution, as there are missing pieces. So, I am curious if you have any recommendations for a client-side router that would pair nicely with Hyper. Thanks!

**Comment by joshgillies** [comment]
`hyperHTML` is intentionally lightweight, and additional functionality eg. routers are left to the users desecration. With that said, there is https://github.com/WebReflection/hyperhtml-app which provides as express like routing experience - but if that doesn't meet your requirements there are a myriad of client side routers on npm.

**Comment by WebReflection** [comment]
Like @joshgillies said, hyperhtml-app is one way, and it's described in here as well:
https://stackoverflow.com/questions/46013494/navigation-with-links-in-hyperhtml-and-hyperhtml-app
