### ISSUE TITLE
Add lazy, inert `wires`

### ISSUE THREAD

**Issue by kaste** [WebReflection/hyperHTML#125]
Proposal. Add lazy or inert templates, which can be later rendered or materialized. 

```

  html(static, ...values) => {static, values}
  materialize({static, values}, obj, type) => DOM


  The relationship to wire is 

  materialize( html`This!`, el, ':mykey') === wire(el, ':mykey')`This`


```

Within `hyperHTML` these 'lazy' templates should be first citizens in the sense that the library will materialize them automatically when possible.

I see two advantages here

1. Using inert templates is a pure function, and comes at almost zero cost

```

  let title = html`<h1>${'The title'}</h1>`
  let flag = false
  hyper`${ flag ? title : ''}` 
  // => ''

```

Running the above will not have the cost of actually creating a `fragment`, parsing/upgrading a template etc. (I'm aware of that often these conditionals can be moved around and manually refactored/optimized. That's more an issue of this example, not of the pattern to have lazy computations when possible)

2. A user can decide at a later point how she actually wants to wire these snippets. 

```

  function Title(title) {
    return wire(/* what can I possibly put here */)`<h1>${title}</h1>`
  }

  // vs. 

  function Title(title) {
    return html`<h1>${title}</h1>`
  }


```

Within the function `Title` I have no good reference obj and/or key which I could use for `wire`. Either I use `wire()` which always works, but is not efficient, or I had to pass in a ref and key, which is otherwise not a concern of `Title` at all.

------

In general, automatic 'materialization' within `render` should be straight forward, because we have good reference objects (the nodes) and keys (the hole indexes).

```

  let title = Title('Hi')
  bind()`<span>${title}    ${title}</span>`
           ^       ^         ^
           |       |         |
          node   index=0     |
                            index=1


```

We could probably wire the first title like `wire(node, '--_-0--')` and likewise the second `wire(node, '--_-1--')`

**Comment by WebReflection** [comment]
I start believing you'd be better of with `lit-html` here where you're locked in into its lazy evaluation graph.

With hyperHTML you can already do hyper`<h1>${title}</h1>` and it's not expensive unless it's a repeated 120 times per second operation.

In that case you can simply use hyper.Components which give you a reference for free and by default.

hyperHTML is already fast, I've decided every issue that mention "beter performance" without providing tests, benchmarks, and use cases, will be closed as speculation/won't fix.

**Comment by WebReflection** [comment]
P.S. the fact you can ``` document.body.appendChild(hyper`<p>hello</p>`) ``` it's a strength of the library that won't get lost any time soon (or ever)
