### ISSUE TITLE
Cannot return html from an intent 

### ISSUE THREAD

**Issue by JSteunou** [WebReflection/hyperHTML#126]
I'm trying to use a custom intent, that should return some html, but if I return 

```
wire()`<div><p>${foo}</p></div>`
```

I get an error 

```
TypeError: this[(i - 1)] is not a function
    at Array.update (index.js:1262)
    at DocumentFragment.render (index.js:199)
    at update (index.js:1346)```

**Comment by JSteunou** [comment]
if I return ```{html: `<div><p>${foo}</p></div>`}``` instead it works

**Comment by WebReflection** [comment]
I don't have enough information.

returning ``` {any: wire()`<div><p>${foo}</p></div>`} ``` should work as proven by tests, right?

**Comment by WebReflection** [comment]
please provide a fully testable failing case if my latest reply doesn't work, thanks

**Comment by JSteunou** [comment]
Sorry find the issue (me), I have an attribute with mixed up string and template string :crying_cat_face:

**Comment by WebReflection** [comment]
yeah, partial attributes are a non-sense for the DOM hence it won't quite possibly ever work in here, as described by the documentation.

Glad you solved though.

Regards
