### ISSUE TITLE
textarea TypeError

### ISSUE THREAD

**Issue by cmbro** [WebReflection/hyperHTML#128]
Am I missing something with [this ](https://codepen.io/cmbro/pen/mBvoLX?editors=0010)simple textarea example:
```
var data = {message: 'Hello hyperHTML!'};
hyperHTML.bind(document.querySelector('#app'))`<textarea>${data.message}</textarea>`;
```
Result:
![image](https://user-images.githubusercontent.com/12277158/31785657-82256cbe-b4cb-11e7-87be-32ae3a661657.png)
With the error:
```diff
- Uncaught TypeError: this[(e - 1)] is not a function
```

**Comment by WebReflection** [comment]
Nice bug! AFAIK this is a textarea related issue only, 'cause it doesn't accept nodes.

for the time being, use this instead:
```js
var data = {message: 'Hello hyperHTML!'};
hyperHTML.bind(document.querySelector('#app'))`<textarea value=${data.message}></textarea>`;
```

will fix ASAP, thanks for the report

**Comment by WebReflection** [comment]
Fixed
