### ISSUE TITLE
An  attributeChangedCallback from a custom element is called with the 'hyper' value initially

### ISSUE THREAD

**Issue by kaste** [WebReflection/hyperHTML#129]
I have a codepen https://codepen.io/anon/pen/MExpme?editors=1010

To restate the issue title, the `attributeChangedCallback` gets called with something like `_hyper: 559820609;`, and then again with the correct user value. 

Expected behavior is that I get exactly one call with the user value.

**Comment by WebReflection** [comment]
unfortunately if you bind content that's injected directly in the DOM, you can see the correct behavior through my fork of your pen:
https://codepen.io/WebReflection/pen/rGRGEP?editors=0010

However, this can be annoying so I'll try to fix it before v2

**Comment by WebReflection** [comment]
You can see everything is now fine. Regards

**Comment by kaste** [comment]
This looks like a reasonable commit. 👍
