### ISSUE TITLE
Universal hyperHTML / hyperHTML-be ?

### ISSUE THREAD

**Issue by WebReflection** [WebReflection/hyperHTML#13]
I don't see why `hyperHTML` wouldn't be usable to render on the server side templates of HTML with the following features:

  - [x] automatically html escaped text content
  - [x] automatically sanitized attributes
  - [x] smart inline event handlers assignment (destructured/delegated)
  - [x] automatic raw HTML injection

Basically, a 1:1 representation as string of what `hyperHTML` would produce at runtime on the client.

**Comment by marcoscaceres** [comment]
Random thought... might be nice to also do large templates in Web Workers if this was supported.

**Comment by WebReflection** [comment]
I think everything non DOM related shouldn't be part of `hyperHTML` module 'cause I'd like to keep it as simple and as small as possible for the Web.

However, using exact same API I'd like to be able to create the following:
```js
update(info) {
  return render`
    <form action="${info.target}">
      <label>
        ${info.label}
        <input type="checkbox">
      </label>
      <input type="submit">
    </form>
  `;
}
```

And have it cached as the following equivalent operation:
```js
update(info) {
  return [
    '<form action="', sanitize(info.target), '">\
      <label>',
    '    ', text(info.label),
    '  </label>\
      <input type="submit">\
    </form>'
  ].join('');
}
```
With the 3 statics parts of the template and the two already known callback that will return the content through their invoke, simulating:
```js
function asText(statics, ...values) {
  const out = [statics[0]];
  const callbacks = cache.for(statics);
  for (let i = 1; i < statics.length; i++)
    out[i] = callbacks[i - 1](values) + statics[i];
  return out.join('');
}
```
which should perform as "_close to the metal_" as possible.

Users use one API, everyone can benefits from its performance boost.

Would Workers benefit from what I've described?

**Comment by WebReflection** [comment]
this is actually happening in this repository:
https://github.com/WebReflection/viperHTML

**Comment by marcoscaceres** [comment]
Watching that one....

**Comment by WebReflection** [comment]
done https://github.com/WebReflection/viperHTML 🎉

**Comment by marcoscaceres** [comment]
Awesome work! Looking forward to using it.
