### ISSUE TITLE
Too restricted when it comes to attribute names

### ISSUE THREAD

**Issue by kaste** [WebReflection/hyperHTML#130]
Again a CodePen https://codepen.io/anon/pen/Qqovyd?editors=1010

Attribute names like `$foo` or `foo.bar` throw an exception. E.g.

```
<my-span $foo=${'BAR'}></my-span>
```

**Comment by WebReflection** [comment]
I’ve used standard attribute names from W3C ... you should too?

**Comment by kaste** [comment]
These are standard names https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

Relevant invalid chars are only ``U+0020 SPACE, U+0022 ("), U+0027 ('), U+003E (>), U+002F (/), U+003D (=)``

**Comment by WebReflection** [comment]
will double check ... I'm sure tabs and many others are not allowed as well

**Comment by WebReflection** [comment]
latest version has `[ \f\n\r\t\/>"'=]+` enabled for attribute names and a test that validates `$foo` is recognized

**Comment by WebReflection** [comment]
P.S. watch out SVG elements are from XML land and the rules used before where for XML

**Comment by WebReflection** [comment]
FYI , during the refactoring it came out there were reasons for the restriction.

```js
document.createAttribute('$foo');
```

If you try that in console, you'll see:

> Uncaught DOMException: Failed to execute 'createAttribute' on 'Document': The qualified name provided ('$foo') contains the invalid name-start character '$'.

Now, the "funny" part is that if you create an attribute named as such via html everything is fine in Chrome, but not in IE/Edge.

This is some headsup you should really try to stick with less problematic attribute names because if IE throws on DOM, hyper will follow and it won't fix this behavior.

**Comment by kaste** [comment]
Ah well, I know that you can't create them via the usual DOM methods. But you can put them in `html` bc that's a different spec. Edge has no problem here, I think. 

![image](https://user-images.githubusercontent.com/8558/32771862-71b79740-c924-11e7-9dfe-d6c589c8265a.png)

Aside, **I** never use funky `$` in attribute names, but custom elements can have some funky custom property names bc the usually map to JS naming conventions.

**Comment by WebReflection** [comment]
That’s foo$ , not $foo ... read carefully the error message 😉

**Comment by papas-source** [comment]
Well, 

`document.createAttribute('foo$');`

also throws an error, 

`Uncaught DOMException: Failed to execute 'createAttribute' on 'Document': The qualified name provided ('foo$') contains the invalid character '$' ...`

so, even if it is not `name-start` it is invalid nevertheless as far as chrome is concerned :/

**Comment by WebReflection** [comment]
to provide more context, if you create a node with funny attribute like the following one, it's OK

```js
document.body.innerHTML = '<p $foo=123></p>';
```

Now, if you grab that attribute and you try to clone it, IE/Edge throws errors so ... again, it's not too wise to use weird chars in attributes.

```js
// fails in IE/Edge, might work elsewhere, still not nice to deal with
document.body.firstChild.attributes['$foo'].cloneNode(true)
```

**Comment by papas-source** [comment]
Works on Chrome
![image](https://user-images.githubusercontent.com/3933935/32779161-57683e6e-c945-11e7-9850-25e295539c71.png)



Works in Safari
![image](https://user-images.githubusercontent.com/3933935/32779278-bf1046c4-c945-11e7-9373-33a60a8b2a60.png)



Firefox fails in the innerHTML assignment
![image](https://user-images.githubusercontent.com/3933935/32779224-932bd3a2-c945-11e7-859f-feff7675abd6.png)

**Comment by WebReflection** [comment]
thanks for checking. Yet another reason attributes names should be like those I was accepting before these changes. I'll let them free to throw but I should probably warn in the documentation (although this is Web standards domain, not mine)

**Comment by papas-source** [comment]
I believe you should restrict naming based on the w3c standards. It's the browsers job to conform to these standards. If somebody want to use any non standard characters in attribute naming - before browsers fix this issue - it is their responsibility.

**Comment by WebReflection** [comment]
no reason to go backward ... not my duty to "police" attribute names, as long as I have a way to recognize what might be valid chars.

in other environments where DOM rules don't apply I might also don't care at all (with basicHTML) but yeah, I won't fix/accept bugs related to bad attribute names, they can follow standards.

And btw, standards here are quite ambiguous
