### ISSUE TITLE
Problems with hyperHTML wire

### ISSUE THREAD

**Issue by robhicks** [WebReflection/hyperHTML#133]
Thanks for hyperHTML. 

I'm new to hyperHTML and am having a problem with wire. I have used it in several places to iterate through lists without problem. However, I'm having a problem with a more deeply nested web component. The parent components as well as the one I'm having problems with are native v1 web components. Here is the render function I have in the nested component:
```Javascript
render() {
    // console.log("this._buttons", this._buttons)
    hyper(this.shadowRoot)`
    <style>${css}</style>
    <toolbar>
      ${actions
        .filter(a => this._buttons.includes(a.name))
        // .map(button => {console.log(button); return button;})
        .map(button => wire(button)`<button name="${button.name}" title="${button.title}" onclick="${button.action}" id="${button.id}">${button.name}</button>`)}
    </toolbar>
    <editor contenteditable="true">${this._content}</editor>
    `;
  }
```
When executed, the html in the wire template tag literal does not get added to the DOM. I have debugged into the actions filter and map and it gets to the wire function and everything looks fine to me as I step the wire function. Of course, I'm not exactly familiar with the way the function should work. 

Any help would be greatly appreciated.

**Comment by WebReflection** [comment]
can you please provide a bare minimal example/code-pen/page where I can test the whole thing?

it'd be way easier for me to help in this way, thanks

**Comment by WebReflection** [comment]
FYI: I'll close this by next Tuesday.
