### ISSUE TITLE
Use of 'template' and that lovely IE smell

### ISSUE THREAD

**Issue by cary-smith** [WebReflection/hyperHTML#136]
So I recently ran into an issue when using hyperHTML and a ShadyDOM which I think could be quickly fixed. 

At several points in their code the localName value is checked against 'template' at which point it may execute functionality specific to the actual template type such as ".content". This explodes in IE because there is no polyfill included to accommodate that. 

I noticed you have a [caveate](https://github.com/WebReflection/hyperHTML/blob/8900770e05011771ab443bf3cc8feaa90943a849/index.js#L619) in there to accommodate aframe. To avoid clashes with libraries that expect a template to behave a certain way it may be worthwhile to accommodate them in environments where templates are not available:

```javascript
var hasNativeTemplate = 'content' in document.createElement('template');
function createHTMLFragment(node, html) {
    var fragment;
    var document = node.ownerDocument;
    var container = document.createElement(
      /<(a-\w+)[\s\S]*?>[\s\S]*?<\/\1>/.test(html) || !hasNativeTemplate ?
        'div' : 'template'
    );
//...
}
``` 
Changing to this fixed the issue I ran into with ShadyDOM but I could see it hitting again with newer libraries.

Thoughts?

**Comment by WebReflection** [comment]
Nothing explode. IE has a fallback and it’s tested.

IE also has no shadow Dom .

Can you please provide a failing example?

**Comment by cary-smith** [comment]
Test case is definitely warranted. 

I will update as soon as I have something. May take a bit to unwind from our code to the simplest format. 

Thanks for the quick response.

**Comment by cary-smith** [comment]
Got it!
https://codepen.io/anon/pen/rYNeva?editors=0010

**Comment by WebReflection** [comment]
So, I've removed shady and used this pen to verify IE11:
https://codepen.io/WebReflection/pen/EbxRva?editors=0010

it works. I think you've opened a bug in the wrong place. If shady patches createElement with a bad implementation of the template you should not use it and fallback with no ShadowDOM for IE?

I mean, not using shadow dom just works, so I don't think this is an hyperHTML issue and if IE ends up believing it has a template with a `content` I don't want to be responsible for 3rd parts broken polyfills.

Apologies if this is not the answer you were looking for.

Regards

**Comment by cary-smith** [comment]
No need to reopen but I think you may be misinterpreting the purpose of the request.

hyperHTML uses 'template' as the default when creating an element which I see as a good thing but it does not supply a polyfill for the template element which IE does not support. Other libraries that hyperHTML may be combined with (ShadyDOM is just an example) may expect that if a 'template' element is provided it is fully up to specification and can be used like one. This can cause unnecessary debugging entertainment.

Given the option I would love to see IE die a quick death and offer it as few caveats as possible. Unfortunately to accommodate it, my choices were request a change to hyperHTML (a 2 line change to provide the element more 'native' to the browser) or add a template polyfill to make hyperHTML function properly with other libraries that may have expectations on particular element. I had hoped to avoid unnecessary polyfills because the logic like it already exists to accommodate something like AFrame and would make hyperHTML more compliant for browsers that have no idea what a template is.

Thanks for looking into it!

**Comment by WebReflection** [comment]
AFrame hack is ugly as hell and it will go away in V2.

I am putting the check upfront but this does not mean that if anyone else would use a broken polyfill for template upfront IE will still fail.

I just don't developers feel free to ask me to add every hack here because other libraries/polyfills have problems. Each hack is hard to code cover and once I have dozens ugly hacks, a bloated code, and not anymore 100% code coverage, people will ditch hyperHTML for other libraries that already don't work in most targeted browsers here.

I hooe you understand what I mean. Regardless, having the check at bootstrap once instead of each time might be worth a change.

**Comment by WebReflection** [comment]
P.S. just FYI your change causes other issues (i.e. tables elements)

**Comment by cary-smith** [comment]
I absolutely agree with avoiding hacks whenever possible and am constantly disappointed in IE for foisting their half-compliant browser pains on developers.  

We already have a bunch of "remove when IE is dead" code in place. Adding a polyfill for template won't kill us and if the change I proposed causes more problems than it solves, then its not worth the effort. Not a problem at all.

Thanks again for at least checking and for hyperHTML!

**Comment by WebReflection** [comment]
I’ll find a solution, just not on Sunday 😉

**Comment by cary-smith** [comment]
The more I look at this the more I am unsure it should be patched. Without a compliant polyfill, anything added is a hack and all of it is only for the sake of IE which has a (hopefully very) limited shelf-life. If it's possible then that would be great, but I would say spend you time on more important implementations like V2!

**Comment by WebReflection** [comment]
I think I agree with you
