### ISSUE TITLE
Property binding

### ISSUE THREAD

**Issue by oliverjanik** [WebReflection/hyperHTML#138]
Apologies if this already exists but it would be cool if hyperHTML could perform property set instead of setAttribute.

See the tests here:
https://custom-elements-everywhere.com/

**Comment by oliverjanik** [comment]
My appologies, the following works and uses my defined properties:

```
        return this.html`
        <main>
            ${this.entries.map(e => hh.wire(e)`<ch-entry entry="${this.entries[0]}"></ch-entry>`)}
        </main>`;
```

Where `ch-entry` is my custom element with `entry` setter defined. Rather cool!

Now question remains why is above test showing 26/30?

**Comment by WebReflection** [comment]
Because they are using a broken version.

You should test latest before filing bugs ;-:

**Comment by oliverjanik** [comment]
Andrea, I did test as you can see from the above post. In my version I was missing wire() inside the map and was returning just a string. 

I posted the working version for posterity if anyone comes across this. (Google is very good at indexing Github issues)

Also submitted an issue here: https://github.com/webcomponents/custom-elements-everywhere/issues/112
