### ISSUE TITLE
Tick demo appears broken

### ISSUE THREAD

**Issue by jakearchibald** [WebReflection/hyperHTML#139]
https://webreflection.github.io/hyperHTML/test/tick.html (linked in the readme) just gives me a blank page.

**Comment by WebReflection** [comment]
thanks Jake. Master is under heavy refactoring and both index.js and min.js files are not the real library.

I can put the V1 back there though if you need to demo stuff around

**Comment by WebReflection** [comment]
actually, I've just put them back and I'll try to not drop them until V2 is out.
