### ISSUE TITLE
Suggestion - Template object and render method

### ISSUE THREAD

**Issue by nikhilk** [WebReflection/hyperHTML#141]
Just came across this library ... looks really interesting. Admittedly still understanding all this some more, so this is early thought, but I'll go ahead and share.

If I have understood correctly, this is something I might do:

    s = 'Hello World'
    hyperHTML.bind(document.body)`<h1>${s}</h1>`;

It would be quite interesting to be able to write this:

    document.body.render(hyperHTML(`<h1>${s}</h1>`), { s: 'Hello World' })

What I am getting at is couple of things:

1. Having a method `hyperHTML` that returns an object such as HyperHTMLTemplate.

2. Having a `render` instance method on HTMLElement that uses the resulting template:

   ```
   render(template, data)
   ```

Seems like it would be more intuitive to me. Possible?

May also be interesting to @justinfagnani for lit-html.

**Comment by WebReflection** [comment]
Please see all the examples. It looks like you want handlebar instead of template literals.

The template you want comes out of the box, you need to drop your old template style biases.

**Comment by WebReflection** [comment]
P.S.

```js
// equivalent of your HyperHTMLTemplate thing
function h1(el, info) {
  return hyper(el)`<h1>${info.text}</h1>`;
}

h1(document.body, { text: 'Hello World' });
```

**Comment by WebReflection** [comment]
P.S.2

comparisons: https://viperhtml.js.org/hyperhtml/examples/
documentation: https://viperhtml.js.org/hyperhtml/documentation/

**Comment by WebReflection** [comment]
P.S.3

> May also be interesting to justinfagnani for lit-html.

if you have something to tell to lit-html please do so in their repository, not here. Thank you

**Comment by WebReflection** [comment]
P.S.4 https://www.playstation.com/en-us/explore/ps4/ (sorry, I had to)

**Comment by nikhilk** [comment]
Must have struck a chord there with the lit-html reference. ;)
Not sure about any biases, but thanks for taking the time with the comments!
