### ISSUE TITLE
Quick remark about v2 modules

### ISSUE THREAD

**Issue by JSteunou** [WebReflection/hyperHTML#146]
Hi, 

I was reading your v2 changelog and found this

> using a new folders convention with esm/index.js as main module and cjs/index.js as transformed artifact. This plays very well with packagers too when you import {hyper} from 'hyperhtml/esm'

`index.js` works well using cjs `require` but it seems that es module does not implement / permit this.

**Comment by WebReflection** [comment]
Correct, but rollup and other packagers that use CJS resolution even in ESM work well
