### ISSUE TITLE
React Router v4 (dynamic router)

### ISSUE THREAD

**Issue by janat08** [WebReflection/hyperHTML#158]
Dynamic router as in react version looks cool, any chances it could be ported over? I'm no fan of react, but ability to interpret react components into hyperhtml would be nice. Quick and dirty workaround examples for both routing and using react components would be great.

**Comment by janat08** [comment]
Using react components and ripping off react router are correlated as react router api consists of components.

**Comment by janat08** [comment]
A branch of react for meeting dependencies, such as for the router, but without the virtual dom would be cool.

**Comment by WebReflection** [comment]
I don't know much about react router but you can have a look at [hyperhtml-app](https://github.com/WebReflection/hyperhtml-app) that maybe does already what you are looking for.

Alternatively, there is a project which would make hyper Components more Reactish via JSX, but that's a work in progress/experiment: https://github.com/codemix/babel-plugin-hyperhtml

**Comment by janat08** [comment]
I mispoke, rather than being "dynamic" it uses components to label routes, therefore, allowing recursive routes for example.

**Comment by WebReflection** [comment]
I don't think this is something for `hyperHTML` core anyway, routing and view are two different things so I'd rather hope for a third parts project that does what you are looking for, hence there's not much to do in here.

Closing for now, feel free to reference this "issue" if you fioind a project that de-couple React-v4 like routing with JSX.
