### ISSUE TITLE
SVG attributes error when creating with wire

### ISSUE THREAD

**Issue by web3d0** [WebReflection/hyperHTML#159]
```
const locations = Array.from(Array(100), () =>
	[Math.random() * 300 >> 0, Math.random() * 150 >> 0]);

bind(document.getElementById('blah'))` // <div id="blah"> in html file
	<svg fill="blue">
		${locations.map(loc => wire(loc, 'svg')`
			<circle cx=${loc[0]} cy=${loc[1]} r="1"></circle>
		`)}
	</svg>	
`;
```

results in error:

```
Error: <circle> attribute cx: Expected length, "_hyper: -8538762…".
  hasContent	
  createFragment	
  createTemplate	
  upgrade	
  render	
  (anonymous function)	
  locations.map.loc	
```
Stepping through shows the innerHTML is being set with _hyper:-8538762 before the actual values are inserted into the placeholders. This only seems to happen on the first element, and doesn't seem to happen for the HyperHTML demos... where is this going wrong?

**Comment by web3d0** [comment]
This is not a partial attribute issue. Changing it to have both variables in a nested ${``} results in a:

    this[(i - 1)] is not a function

error. Reducing it to one variable results in the same "Expected length" error as before.

**Comment by web3d0** [comment]
It's a bug in Chromium with over-eager reporting.

**Comment by albertosantini** [comment]
Well, it is reported also in FF, like a parsing error.

@web3d0 please, bug link?

**Comment by web3d0** [comment]
It shows an error in Safari too, but Andrea confirmed on Twitter that the code does work on all browsers and he raised the bug report for Chrominium.

**Comment by albertosantini** [comment]
@web3d0 I saw the tweets. Thanks.

> that error is *not* a real error, just some engine being overly logging.
Indeed not every browser shows it but also everything *works* as expected.

> You can freely *ignore* that error and it’ll never go away but it’ll never cause issues too.

**Comment by web3d0** [comment]
I must admit to pondering about outputting the string directly when created, then the placeholder structure for updates. I'm still poking around in the code and learning Andrea's style of code - very compact!
