### ISSUE TITLE
Unable to get the JSON object via attribute

### ISSUE THREAD

**Issue by techpanga** [WebReflection/hyperHTML#162]
Is it possible to pass JSON objects( using variables) via attributes?

var loginModel = {user:'john',password:'doe'};
this.html<my-login data-model=${loginModel} ></my-login>

With in MyLogin component, I am unable to get the attribute using this.dataset.model

Please help.

**Comment by WebReflection** [comment]
you can pass `<div data=${loginModel}>` because data is a special property, and retrieve `data` directly after, otherwise you are violating HTML attributes that are based on text, included datasets.

More on attributes here:
https://viperhtml.js.org/hyperhtml/documentation/#essentials-4

**Comment by chrismbeckett** [comment]
I can't find any documentation on a *data* special property. Is this a feature of HTML or something built into HyperHTML?

**Comment by WebReflection** [comment]
Hi @chrismbeckett , `data` is a special case in `hyperHTML`, meaning it works the same in `HyperHTMLElement` too. I need to update the documentation about it, sorry.

**Comment by chrismbeckett** [comment]
Thanks for the confirmation - that helps a lot. Very useful feature.
