### ISSUE TITLE
IE11 breaks on custom attribute interpolation with webcomponents-sd-ce.js polyfill

### ISSUE THREAD

**Issue by pmowrer** [WebReflection/hyperHTML#177]
When using `hyperhtml` with [`webcomponents-sd-ce.js`](https://github.com/webcomponents/webcomponentsjs) and interpolating a custom attribute, IE11 throws `HierarchyRequestError`. It works fine in every other browser I tested, including Edge 14 and Safari 9.1.

```js
var html = hyperHTML.bind(document.body);

html`
  <div custom="${true}">test</div>
`
```
[CodePen](https://codepen.io/stiggler/pen/YeXeWd?editors=0011)

It seems to work for non-custom attributes. This works:

```js
var html = hyperHTML.bind(document.body);

html`
  <div disabled="${true}">test</div>
  <li value="${true}">test</li>
`
```

I suppose this is likely a bug with the monkey patching performed by the polyfill. What are your thoughts?

**Comment by WebReflection** [comment]
if you remove the polyfill, which is completely useless in your example, does IE11 throws any error?

**Comment by WebReflection** [comment]
... and btw, about these cases, my thoughts in a nutshell: https://twitter.com/WebReflection/status/956480147502313472

**Comment by pmowrer** [comment]
> if you remove the polyfill, which is completely useless in your example, does IE11 throws any error?
Yes. I didn't include any code that depends on the polyfill in the example since it isn't necessary to reproduce the issue.

**Comment by pmowrer** [comment]
Narrowed down the actual [issue](https://github.com/webcomponents/shadydom/issues/211). Sorry about the noise.

**Comment by WebReflection** [comment]
awesome finding (for them to fix) ... I don't want to say _told'ya so_ ... but ... **[told-ya so](https://twitter.com/WebReflection/status/956480147502313472)** 😂😂😂
