### ISSUE TITLE
Removal of unused css

### ISSUE THREAD

**Issue by ansarizafar** [WebReflection/hyperHTML#179]
I want to use semantic-ui/Tailwindcss with hyperhtml. These are big css files and I am trying to use purgejs webpack plugin with poi to remove unused css. It seems that purgejs plugin configuration is working fine but the pluing unable to find used css. Any idea how it can be done?

**Comment by WebReflection** [comment]
I've honestly no idea what you're talking about.

This is a very poor bug report:

  * not a link
  * not even related to the library (css?)
  * not a demo, an example, a snippet

Please file reasonable bugs so that neither you nor me would waste any extra time.

Thank you.

**Comment by ansarizafar** [comment]
I am experimenting with amazing hyperhtml and I want to use it for my next project that is why trying to identify all the requirements of a real world project. 

Most real world projects use some css framework like Bootstrape, Foundation, Semantic-ui, Tailwindcss etc. These frameworks are big in terms of file size. Tools like Purgejs https://www.purgecss.com/ are used to remove unused css from a project to reduce bundle size. I have used these tools successfully with other frameworks like VueJS etc but these tools with same configuration are not working with Hyperhtml as this library is using template literals that is why purgejs is unable to identify css classes used in templates. 

This is a real issue specially If you are building a PWA. I hope you can help finding a solution to this issue. Here is sample repo https://github.com/ansarizafar/hyperhtml

Thank you for creating amazing Hyperhtml.

**Comment by WebReflection** [comment]
you could use same strategy used by viper-news, it's described in here:
https://github.com/WebReflection/viperHTML#handy-patterns

the `render` would be `this.html` and the `model` any extra data you need per update.

In few words you'd create [*.html](https://github.com/WebReflection/viper-news/blob/master/shared/template/item.html) files, you would transform them [as CJS modules](https://github.com/WebReflection/viper-news/blob/master/shared/view/item.js) and you would end up with components like:

```js
const { Component } = require("hyperhtml/umd");

const update = require("../views/header.js");

export default class Header extends Component {

  render() {
    return update(this.html, this);
  }

}
```

In this way you can pass the folder with all HTML components to whatever too you want and it will work (should?) out of the box.

**Comment by ansarizafar** [comment]
There should be a better and developer friendly way of doing this, like Vuejs webpack loader https://vue-loader.vuejs.org/en/

Tooling is very important for any front end framework to succeed in this very competitive world. Thanks for the solution.

**Comment by WebReflection** [comment]
> like Vuejs

VueJS is great because it has [many active contributors](https://github.com/vuejs/vue#contribution), not just people filing requests 😅 + Evan You works on it full time thanks to donations.

**Comment by ansarizafar** [comment]
I am not an expert like you otherwise I could have contributed and created all the required tools and missing/suggested features. I wish I could.

> not just people filing requests sweat_smile 

I understand building and working on an open source project of this scale is a huge task but comments like this will not help building a sizable community, contributors (and donations) around this amazing project and will keep early adopters away. Every sincere suggestion, request and opinion should be respected.

**Comment by WebReflection** [comment]
> comments like this will not help building a sizable community

this whole issue is not helping neither.

This project needs contributors, not people that constantly point at how better are all other frameworks with entire companies behind or 164 contributors.

Your name is nowhere in the donators list but you keep asking for the most demanding tasks ever here or in [viperHTML](https://github.com/WebReflection/viperHTML/issues/3).

When you'll be able to file better issues and resize your requests _maybe_ we'll be capable of moving this library forward helping each others, instead of just asking "_why VueJS has all this and not hyperHTML_"

Best Regards

**Comment by ansarizafar** [comment]
No project/framework is perfect and there is no harm in learning from others. 

> "why VueJS has all this and not hyperHTML" 

did I said that? Vuejs also has its own issues that's why I am looking for other options.

I am not pointing at how better are all other frameworks, the references are only given for learning purpose so please take them positively.

> When you'll be able to file better issues and resize your requests maybe we'll be capable of moving this library forward helping each others

I think I have filed real issues and given relevant references/suggestion. If you don't want people to identify/file issues,  give relevant references and ask questions then I don't know how we can help each other and move this awesome project forward.

> Your name is also nowhere in the donators list but you keep asking for the most demanding tasks ever

Money is important but community is more important, not all Vue users are contributors or donating money. Yes Evan is getting $12000/month nowadays but he really worked very hard for years to develop all the features and build a community before he got first donation. Its a chicken & egg problem so I would request you to please be patient and take things positively. You have really created a unique library and I am sure you will succeed both in terms of building a community and earning money. 

If you don't want be use hyperhtml and file issues and ask questions then It's ok. I wish you all the best.     
     
Thanks

**Comment by WebReflection** [comment]
I am patient but I don't have infinite time.

Current roadmap:

  * hyperHTML adoption
  * viperHTML alignment
  * viperHTML for both ESM and CJS

Up next: a way to to have components with scoped CSS but without needing Custom Elements or Shadow DOM.

Once I'll be 100% happy with all the library potentials, I'll start creating surrounding helpers/tools.

Until that, I can only suggest how to solve incompatibilities with third parts tools.

Best Regards

**Comment by WebReflection** [comment]
Solution: https://github.com/WebReflection/hyperHTML/issues/180
