### ISSUE TITLE
Removal of unused css - Problem solved

### ISSUE THREAD

**Issue by ansarizafar** [WebReflection/hyperHTML#180]
I am filing this issue for only information as the related issue is locked and there is no other place to share the solution @WebReflection you can close it and If your interested then we can use https://gitter.im or discord for community discussions.

The only problem in poi configuration was missing ** now unused css can be removed, If you are using any css framework like bootstrape, semantic-ui etc. The result dev bundle size 3.2mb and production build size just 12kb

Wrong
````
 paths:  glob.sync(`${PATHS.src}/*.js`),
````
Correct
````
 paths:  glob.sync(`${PATHS.src}/**/*.js`)
````

**Comment by WebReflection** [comment]
The gitter lobby is here: https://t.co/Fxnf1fRmYd
Thanks for reporting the solution.
