### ISSUE TITLE
Error when trying to render from raw string

### ISSUE THREAD

**Issue by tristancaron** [WebReflection/hyperHTML#181]
Using this code

```
const render = hyperHTML(document.body)

render("<div>Hello world!</div>")
```

Returns
```
min.js:1 Uncaught TypeError: e.join is not a function
    at HTMLBodyElement.u (min.js:1)
    at HTMLBodyElement.a (min.js:1)
    at HTMLBodyElement.o (min.js:1)
    at <anonymous>:1:1
```

**Comment by WebReflection** [comment]
you are missing the whole point about this library. you need template literals. these will work eventually even if transpiled.

```js
const render = hyperHTML(document.body);
render`<div>Hello world!</div>`;
```

**Comment by WebReflection** [comment]
[Documentation](https://viperhtml.js.org/hyperhtml/documentation/)

**Comment by tristancaron** [comment]
Yes, I read this. But I'm not using JS and I would have loved to be able to use this library. I guess I will use something else.

**Comment by WebReflection** [comment]
> But I'm not using JS and I would have loved to be able to use this library.

what do you mean? hyperHTML works in whatever Web you are creating. Actually, it works even on the [backend](https://github.com/WebReflection/viperHTML) and on [native](https://github.com/WebReflection/nativeHTML).

The whole point is about template literals and it's explained in the documentation.

> I guess I will use something else.

I guess go ahead :man_shrugging:

**Comment by tristancaron** [comment]
Kotlin, Scala, Dart etc

**Comment by WebReflection** [comment]
oh gosh ... I didn't know Dart had no template literals ... OK, this is an experiment meant to work for developers that for some reason cannot transpile code:
https://gist.github.com/WebReflection/9e79afe2ac808b0d726c7ed37b476fdc

It patched `hyperHTML` methods `bind` and `wire` and it adds an `$` helper.
```js
const {bind, wire, $} = hyperHTML;
bind(document.body)
('<p>Hello ',
  $(wire()('<strong>World</strong>')),
'!</p>');
```

**Comment by WebReflection** [comment]
OK, it's officially in the package now, it's called `no.js` for people that don't have JS or people targeting old browsers without the ability to transpile in their environments.

Your initial example also actually works now.

Include hyperHTML:
https://unpkg.com/hyperhtml@latest/min.js

Then add later on the `no.js` patch:
https://unpkg.com/hyperhtml@latest/no.js

I hope this works, please file another ticket if it doesn't or if the package should be different, thanks.

**Comment by web3d0** [comment]
@tristancaron He's right, you did miss the point. You need to be using the backticks for template literals, and then you can run everything else through that. You haven't even one step 1.
