### ISSUE TITLE
Support for compilation to standalone components 

### ISSUE THREAD

**Issue by oliverjanik** [WebReflection/hyperHTML#183]
Say I have 40 web components that I want to package separately and publish them as separate packages and I don't want to have them take on a hyperhtml dependency or bundle hyperhtml each time.

This is something similar to what stencil.js does.

Would this be possible with your current architecture?

**Comment by WebReflection** [comment]
> I don't want to have them take on a hyperhtml dependency

how do you package your WebComponents ? 'cause if it's via HTML you can put yourself a script like the following somewhere, right?
```js
<script src="https://unpkg.com/hyperhtml-element"></script>
```

Otherwise I'm not sure how it could be possible because all parts of the library are needed to make it works.

**Comment by oliverjanik** [comment]
I meant for distribution to other devs who don't necessarily use hyperhtml (like for use in angular4)?

But you bring up a good point I'm not sure how much overhead stencil.js adds.

**Comment by WebReflection** [comment]
AFAIK stencil also relies on [this polypill](https://github.com/WebReflection/document-register-element) so it's hard to believe it ships without overhead/libraries/polyfills included

**Comment by papas-source** [comment]
svelte does something similar

**Comment by pinguxx** [comment]
As an idea, what i end up doing, was to create a file with the "framework" which pretty much included hyperhtml and hyperhtml-element and the document register element polyfill (you can of course include other polyfills like promises, etc), and then pack the elements individually and in my case a bundle with everything, i use rollup for this

**Comment by WebReflection** [comment]
FWIW if you include [hyperHTML-Element](https://github.com/WebReflection/hyperHTML-Element) you won't need to also include hyperHTML 'cause it ships automatically with the former

**Comment by WebReflection** [comment]
The way custom elements can inter-operate with each others is via `customRegistry.whenDefined('custon-name').then(...)`, which I've always found a bit awkward to be honest, but it's great for asynchronous component loading.

What if all you need is an entry point that brings in on first request only hyperHTML?

```js
var whenDefined = (function () {
  var queue = [];
  var notLoading = true;
  var loadHyperHTML = true;
  return whenDefined;
  function load(name) {
    script(onload).src = whenDefined.base + name + '.js';
  }
  function onload() {
    var parentNode = this.parentNode;
    if (parentNode) parentNode.removeChild(this);
    queue.splice(0).forEach(load);
  }
  function script(onload) {
    var script = document.createElement('script');
    script.onload = onload;
    return document.head.appendChild(script);
  }
  function whenDefined(name) {
    if (loadHyperHTML) {
      queue.push(name);
      if (notLoading) {
        notLoading = false;
        script(function () {
          loadHyperHTML = false;
          onload.call(this);
        }).src = 'https://unpkg.com/hyperhtml';
      }
    } else {
      var Class = customElements.get(name);
      if (Class) return Promise.resolve(Class);
      else load(name);
    }
    return new Promise(function (resolve) {
      customElements
        .whenDefined(name)
        .then(function () {
          resolve(customElements.get(name));
        });
    });
  }
}());
```

The way you configure such loader is by setting `whenDefined.base = 'js/';`, as example, where all custom elements are.

Let's say we have a `my-component.js` in the `./js/` folder.
```js
class MyComponent extends HTMLElement {
  connectedCallback() {
    console.log('hello hyperHTML');
    hyperHTML.bind(document.body)
      `<h1>hello component</h1>`;
  }
}

customElements.define('my-component', MyComponent);
```

Once you have that in place, you can test the following example code:
```js
// trash the document and place a component there (single node, you can omit the closing here)
document.body.innerHTML = '<my-component />';

// whenever you need the component
whenDefined('my-component').then(console.log);
```

What happens next is that you load `hyperHTML` once per application lifecycle, and then you'll load all components you required in the meanwhile then when hyperHTML is in as well as all your components (one in this case) you'll see in console `hello hyperHTML` followed by the class logged via console, and also with the document.body showing `hello component`.

There, you have portable custom elements with a lazy dependency loaded once and based on a CDN plus the multiple asynchronous components loaders included.

The loader size is 339 bytes gzipped.
```js
var whenDefined=function(){function c(a){d(e).src=f.base+a+".js"}function e(){var a=this.parentNode;a&&a.removeChild(this);g.splice(0).forEach(c)}function d(a){var b=document.createElement("script");b.onload=a;return document.head.appendChild(b)}function f(a){if(h)g.push(a),k&&(k=!1,d(function(){h=!1;e.call(this)}).src="https://unpkg.com/hyperhtml");else{var b=customElements.get(a);if(b)return Promise.resolve(b);c(a)}return new Promise(function(b){customElements.whenDefined(a).then(function(){b(customElements.get(a))})})}
var g=[],k=!0,h=!0;return f}();
```

What do you think?

**Comment by WebReflection** [comment]
closing this if no extra question is left
