### ISSUE TITLE
Uncaught SyntaxError: Octal escape sequences are not allowed in strict mode.

### ISSUE THREAD

**Issue by synaptiko** [WebReflection/hyperHTML#184]
I'm getting the error on CodePen examples in the docs for the latest version of hyperHTML https://unpkg.com/hyperhtml@2.5.8/min.js

For example for this https://codepen.io/WebReflection/pen/qXXgJd?editors=0010 there is in console:
```
Uncaught SyntaxError: Octal escape sequences are not allowed in strict mode.
```

**Comment by WebReflection** [comment]
Sorry for that, 2.5.9 is fine ... something went wrong with uglify-js output (the index.js was indeed fine)
