### ISSUE TITLE
[Suggestion] Add types to hyperHTML

### ISSUE THREAD

**Issue by zaclummys** [WebReflection/hyperHTML#187]
By adding types to support Typescript, you can increase the reach of this package and make its use more organic.

https://github.com/DefinitelyTyped/DefinitelyTyped/

**Comment by WebReflection** [comment]
I don't have experience with ... any help ? here various signatures, I think types when it comes to template literals tag functions might mislead.

```js
bind(node)`content` === node
// but
bind(node) is a Function
```js

Anyway, following the current signature

```
bind(node:HTMLElement):Function
wire(void|any):Function
wire(void|any,info:string):Function
Component(definition):class
```

Maybe it would make sense to return HyperTemplateFunction and define it somewhere else as interface?

Any help to do this right woule be appreciated.

**Comment by zaclummys** [comment]
I'll look deeper into the package and make a pull request as a recommendation. Thanks for the welcome.

**Comment by WebReflection** [comment]
types are in 2.6 :tada: :balloon:
