### ISSUE TITLE
Unquoted onsubmit in a form doesn't render as expected

### ISSUE THREAD

**Issue by davidmerrique** [WebReflection/hyperHTML#188]
Hi, just found a bug.

```javascript
hyperHTML.wire()`
<form onsubmit=${onsubmit}>
  <input type="email"/>
  <button>Submit</button>
</form>
`;
```

```html
<!-- output -->
<form>
  <input type="email"/>
</form>
<button>Submit</button>
```

Everything else in the form is rendered outside of the form element.

Putting quotes around (`onsubmit="${onsubmit}"`) fixes it.

Related to #172?

Thanks

**Comment by WebReflection** [comment]
Sorry ... what? You should never see method, have you confused hyperHTML with viperHTML?

**Comment by davidmerrique** [comment]
@WebReflection Check out this pen https://codepen.io/davidmerrique/pen/ddONwe

It actually looks like the problem is with the `/` in input:
Not working `<input type="email"/>`
Working `<input type="email">`

**Comment by WebReflection** [comment]
gotcha, good test case there.

```js
function onsubmit() {
  console.log('not working')
}

const working = hyperHTML.wire()`
<form onsubmit=${onsubmit}>
  <input type="email" placeholder="Working">
  <button>Button</button>
</form>
`

const notWorking = hyperHTML.wire()`
<form onsubmit=${onsubmit}>
  <input type="email" placeholder="Not Working"/>
  <button>Button</button>
</form>
`

const butThisWorks = hyperHTML.wire()`
<form onsubmit="${onsubmit}">
  <input type="email" placeholder="But this is working"/>
  <button>Button</button>
</form>
`

hyperHTML.bind(document.body)`${[
  working,
  butThisWorks,
  notWorking
]}`;
```

**Comment by WebReflection** [comment]
@davidmerrique if you change your external script with just `https://unpkg.com/hyperhtml` that brings in `2.5.10` you'll see the issue has been fixed.

Thanks for filing this and writing the demo, all use cases (and more) are now officially tested.
https://github.com/WebReflection/hyperHTML/blob/master/test/test.js#L998-L1033

This bug helped a lot to make latest self-closing tag changes truly reliable, awesome stuff!

**Comment by davidmerrique** [comment]
@WebReflection Thanks so much!
