### ISSUE TITLE
Leftovers in test/boot-speed.html ?

### ISSUE THREAD

**Issue by ivancuric** [WebReflection/hyperHTML#20]
https://github.com/WebReflection/hyperHTML/blob/master/test/boot-speed.html#L16
https://github.com/WebReflection/hyperHTML/blob/master/test/boot-speed.html#L37

Seems like some leftovers on lines 16 and 37:
```
16:    <my-tag :items='items'></my-tag>
37:    boot.textContent = Date.now() - start;
```

**Comment by WebReflection** [comment]
that's just a copy and paste from this:
http://plnkr.co/edit/KTqvngteLKmX3ZXMDyZO?p=preview

but what's in test is not part of the library so cannot be raised as a bug because it cannot cause any problem, right?

**Comment by WebReflection** [comment]
TL;DR there are few pages there for reasons that might not even be related with the lib itself. Just runtime tests for me as developer, nothing to be concerned about for users.
