### ISSUE TITLE
Uncaught SyntaxError: Octal escape sequences are not allowed in strict mode.

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/hyperHTML#203]
With `hyperHTML 2.5.12` I see that error in https://codepen.io/WebReflection/pen/ZJbvLa?editors=0010
It is an example you use in PR about hyper.Component.

**Comment by ripter** [comment]
I see the error on my versions and even the example listed in the docs: https://webreflection.github.io/hyperHTML/test/tick.html

**Comment by albertosantini** [comment]
See also https://github.com/WebReflection/hyperHTML/issues/184.

**Comment by WebReflection** [comment]
I hopefully published 2.5.13 without this issue.

My deep apologies for this glitch between Linux/macOS publishing, I'll make myself sure every other time I'll create the min.js via Linux and never via Mac.

Please re-open this issue if 2.5.13 didn't fix it, thanks.
