### ISSUE TITLE
Can you include pre-compiled ESM module in your NPM package?

### ISSUE THREAD

**Issue by oliverjanik** [WebReflection/hyperHTML#212]
I just did npm i hyperhtml and got the 2.6 package and it contains esm folder with index.js, which seems to be the source code split into several other modules.

Would it be possible to add a precompiled esm version that I can just chuck into my project and import from my files?

I'm not using any bundler just pure ESM for this experimental project.

**Comment by oliverjanik** [comment]
For anyone interested. This is super simple to do using rollup:

```
rollup esm/index.js -o hyper.js -f es
```

**Comment by WebReflection** [comment]
> I'm not using any bundler just pure ESM for this experimental project.

Then you can always `import {hyper} from 'https://unpkg.com/hyperhtml?module';`, right?

**Comment by WebReflection** [comment]
I am going to close this as there's no action for me to take.

There are various ways to import in every sauce this project and your rollup one liner is just another example (thanks for that).

Regards
