### ISSUE TITLE
Textarea with empty string

### ISSUE THREAD

**Issue by Fredx87** [WebReflection/hyperHTML#218]
When the content of a textarea is an empty string, the content is replaced with an HTML comment:
https://codepen.io/anon/pen/LQrBKR?editors=0010

(Similar to the alredy resolved issue https://github.com/WebReflection/hyperHTML/issues/200)

**Comment by pinguxx** [comment]
not a fix in hyperhtml but maybe do
<textarea value="${data.message}"></textarea>

**Comment by WebReflection** [comment]
this is a regression ... sorry for the inconvenience ... looking now

**Comment by WebReflection** [comment]
Apologies again. Version `2.7.2` with a definitive fix for all the possibilities.

It was a silly fix the one in 200, now it's for sure cleaned no matter what.
