### ISSUE TITLE
Array Re-rendering

### ISSUE THREAD

**Issue by cpinnix** [WebReflection/hyperHTML#219]
Hello! I found an issue with DOM elements being re-rendered depending on the position of elements removed in an array. Reproducer in a codepen here https://codepen.io/cpinnix/pen/vRVxer. Basically, we are working through a carousel example where we display a slice of items within a larger array based on an index. When we move the index backwards, elements do not re-render as expected, but if we move forward, all elements re-render. It's easy to see in Chrome developer tools.

**Comment by WebReflection** [comment]
just bebug `subset` to realize everything works as expected ?

**Comment by WebReflection** [comment]
P.S. this is a bootstrap carousel: https://codepen.io/WebReflection/pen/zpeKXz and as you can see is very simple to make lists render infinitely/recursively but of course you need to understand how to move a list forward or backward. Once you get that, you'll see everything is fine here, cause the [domdiff](https://github.com/WebReflection/domdiff#domdiff) engine is 100% code covered with pretty much all use cases :wink: 

if that's not the case, domdiff is the repository you are looking for to file a bug.
