### ISSUE TITLE
Objects inside template literals throws

### ISSUE THREAD

**Issue by r0mflip** [WebReflection/hyperHTML#228]
I was just testing around with template literals and tried to do something like
``` js
const data = {success: true};
const render = hyperHTML.bind(document.body);

render`
  <div>${data}</div>
`;
```
I was expecting to get at least `[object Object]` inside a div but it just throws an error
```
Uncaught TypeError: Cannot use 'in' operator to search for 'ELEMENT_NODE' in undefined
```
And I also tried to pass in a function/constructor and expected the function code as output, but got the same error.

Did some debugging and found that `domdiff` doesn't handle objects/functions/constructors. Is this behaviour expected and is there any chance that these type of things will be supported?

This issue might not be relevant here, but just wanted to ask.

> **P.S.** Quite new to hyperHTML and loving it
> Also love hyperHTLM-app and viperHTML and domdiff.
> Finally felt happy to see some VDOMish and templating stuff without any build systems and stuff that just works directly in a browser. I just 🖤️ it.

**Comment by mram** [comment]
> I don't [object Object] is useful to anyone

I totally agree.

> domdiff handles, well ..., dom nodes.

This is where I went wrong 😬

Just wanted to pass JSON data directly to the template strings, Iam probably better off with an explicit call to `JSON.stringify(data, null, '  ')`. Just poking around. Thanks btw.
