### ISSUE TITLE
literally-html syntax highlighter for sublime text??

### ISSUE THREAD

**Issue by thezimmee** [WebReflection/hyperHTML#232]
This is a question, not an issue. Is there a sublime text syntax highlighter like literally-html? If not, any chance of supporting one? Thanks for all your work.

**Comment by WebReflection** [comment]
this question would be probably more appropriate in the literally-html repository but the short answer is no, 'cause I wouldn't know how to do that and I don't use sublime anymore (even if I was one of those that paid for the license)
