### ISSUE TITLE
Component lifecycle of nested component

### ISSUE THREAD

**Issue by gunawanwijaya** [WebReflection/hyperHTML#235]
we need a state management when choosing to use component, but how one can implement this state management in hyperHTML, it seems i can't find any resource on how to do this

when making a component based webapp, the core idea is re-usability so by creating a component Link, we can use it in header menu as a clickable link with padding or even inline in body, e.g.

1. App (container)
2. Header
3. List + ListItem
4. Link

given this situation, we want to create a dynamic Header with a List of Links, so we create an App; map it to create Link components; call Header with props Link components; in Header we call List and read what value that we need to be rendered, since we're passing a Link components, each of this components mapped to ListItem - pretty straightforward - we're rendering the right components.

at first setup a placeholder menu on App, so not breaking the layout, lets say 2 item of links /#0 & /#1; then fetch the menu from a JSON to return what menu that we will create; setState with new menus - nice, we render the new Header with new props; add click event to change App state; then - BOOM - the Header lost all of it's child; when re-render is disabled via `setState({}, false)` the event is properly called & no child is lost; maybe we shouldn't change the parent props directly? well i'm trying CustomEvent but no good; i think something's off with `render()` - any workaround? or solution?

example: https://github.com/gunawanwijaya/gunawanwijaya.github.io/tree/hyper/src/js

addendum, when printing the `this.props`/`this.state` given on each component `render()`, somehow the state is not right(?) is this intentional? or i wrongly called the components?;

1. 2 item of links /#0 & /#1
2. 4 item of links /a, /b, /c & /d
3. 2 item of links /#0 & /#1 (yep back to initial state)

and this is always happening in `render()` but not in `constructor()`, there is no method to revert a state, since the state is created during `get defaultState()`; idk if this is related tho

hyperHTML is fun and unopinionated, it's really nice to code in such simplicity; hope the community grows, more docs & examples, best practices & tips on how to hyperHTML

**Comment by WebReflection** [comment]
can you please reduce the scope of this ticket to the minimum possible example ? I won't have time to help otherwise, not at least in the short term.

Thank you

**Comment by gunawanwijaya** [comment]
The main issue is whenever calling parent `this.setState` from child; parent not properly render the template(all the way down to the child who called the method to change parent state); but when calling `this.setState` directly this issue never happen;

when execute `this.setState` with rerender = false, the template is not affected, therefore i think that there's issue with render()

so in App we wire a Header with dynamic array which contain Link instead of text. Since we're initiating Link creation in App, we also create a click event for this Link (using hyperhtml-app for routing) and also change App state html based on current routing path

App.js
```js
const d = document;

d.root = d.getElementById("root");
const app = require("hyperhtml-app")();
const { Component, bind } = require("hyperhtml/cjs");

const Header = require("./component/Header");
const Link = require("./component/Link");

const URI = "http://localhost:4000";

class App extends Component {
  constructor() {
    super();
    fetch(`${URI}/api/pages.json`)
      .then(b => b.json())
      .then(b =>
        b
          .filter(b => b.permalink && b.menu_index >= 0)
          .sort((a, b) => a.menu_index - b.menu_index)
          .map(b => ({
            item: Link.for({
              text: b.title,
              href: b.url,
              click: () => {
                this.setState({ route: b.url });
                app.navigate(b.url);
              }
            })
          }))
      )
      .then(b => {
        this.setState({ listItems: b });
      });
  }

  get defaultState() {
    return {
      route: "/",
      html: d.getElementById("content").innerHTML,
      listItems: Array(2)
        .fill()
        .map((a, i) => ({
          item: Link.for({
            text: `#${i}`,
            href: `#${i}`,
            click: () => {
              this.setState({ route: `#${i}` });
              app.navigate(`#${i}`);
            }
          })
        }))
    };
  }

  render() {
    return this.html`
    ${new Header({ listItems: this.state.listItems })}
    <p>${this.state.route}</p>
    `;
  }
}

bind(d.root)`${new App()}`;
```

Header.js
```js
const { Component } = require("hyperhtml/cjs");
const List = require("./List");

module.exports = class Header extends Component {
  constructor(args) {
    super().props = args;
    this.setState(this.props);
  }

  get defaultState() {
    return {
      listItems: []
    };
  }

  render() {
    return this.html`
      <header
        class="clear"
        style="${{ background: "#f009" }}"
      >
        ${new List({
          tag: "UL",
          listItems: this.state.listItems,
          listStyle: { display: "inline-block", margin: 0, padding: 0 },
          listItemStyle: { display: "inline-block" }
        })}
      </header>
    `;
  }
};
```

List.js
```js
const { Component } = require("hyperhtml/cjs");

class ListItem extends Component {
  constructor(args) {
    super().props = args;
    this.setState(this.props);
  }

  get defaultState() {
    return {
      listItemStyle: {}
    };
  }

  render() {
    return this.html`
      <li style="${this.state.listItemStyle}">${this.state.item}</li>
    `;
  }
}

module.exports = class List extends Component {
  constructor(args) {
    super().props = args;
    this.setState(this.props);
  }

  get defaultState() {
    return (
      this.props || {
        tag: "UL",
        listItems: [],
        listStyle: {},
        listItemStyle: {}
      }
    );
  }

  render() {
    const li = this.state.listItems.map($ => {
      $.listItemStyle = this.state.listItemStyle;

      return ListItem.for($);
    });

    return this.state.tag.toUpperCase() === "UL"
      ? this.html`<ul style="${this.state.listStyle}">${li}</ul>`
      : this.html`<ol style="${this.state.listStyle}">${li}</ol>`;
  }
};
```

and Link.js
```js
const { Component } = require("hyperhtml/cjs");

module.exports = class Link extends Component {
  constructor(args) {
    super().props = args;
    this.setState(this.props);
  }

  get defaultState() {
    return {
      style: {},
      text: null,
      href: "#",
      click: () => {}
    };
  }

  render() {
    return this.html`
      <a
        style="${this.state.style}"
        href="${this.state.href}"
        onclick="${this.state.click}"
      >${this.state.text}</a>
    `;
  }
};
```

**Comment by WebReflection** [comment]
every `new` and every `.for` in above code create new components each time + you should bubble up events (by doing nothing) and let the parent handle its own state.

But again, can you please reduce to the minimum example possible the issue?

**Comment by gunawanwijaya** [comment]
> But again, can you please reduce to the minimum possible example the issue?

ok so here's the minimum possible example

1. have an App; bind to $("#root")
2. from App create  Link with event that set App state (maybe this is problem??)
3. send an array of Links to new created Header as props/state
4. from Header create new List and forwarding array of Links
5. from List read array of Links we just receive, map to a state and print whatever the state is
6. for some reason, we can update the items by setState in parent (App) all the way down to List; but not with any event from child (Link) that exec parent.setState

what i try to achieve is

1. be able to generate Component on the fly
2. attach an event to it
3. send this new Component to another Component to be rendered later
4. state mutation with child as a caller to parent as a callee & vice versa

**Comment by WebReflection** [comment]
sorry for not being clearer @gunawanwijaya but I mean to reduce the problem to 2 components only. If you keep describing 5 components I cannot easily understand what is the issue. All I can say so far is that:

  1. I would never set the state of a component from one of its child. The DOM is about owning and bubbling, the container owns its children, not vice versa
  2. you are not using weak references, you are creating new content per each render. When you say you don't find your links anymore I don't know what you'd expect since `new Header` will create a new header per each render and `Link.for({fresh: 'new object'})` in a map too

Accordingly, if you can show me a 2 parent/child component example where things fail I can try to help describing what is it that you are doing wrong or what is a bug, if any.

Last, but not least, if you pass `false` to the render and it doesn't render you just used exactly what that `false` flag is about: avoid rendering.

It looks then you have slightly off understanding of how to put things together in an efficient way but I don't want to rewrite your app, I want you to understand the right approach.

So, can you please reduce the scope of the issue to 2 components only?

**Comment by gunawanwijaya** [comment]
the problem is bcs in Header (1st child) we call new List (2nd child) - now working, only if i move the new List to the component where we're trying to set it's state (top level parent);

also now the component is organized and literally hold no complicated logic in the component itself, all the logic now exist in the top level parent (i remember the mvc pattern here)

```js
${new Header({
  content: new List({
    tag: "UL",
    class: "no-scrollbar",
    content: this.state.ofHeaderListItems.map(b => ({
      content: Link.for({
        content: b.title || "#",
        click: e => this.menuClicked(e, b),
        class: b.url === this.state.route ? "active" : null,
        href: b.url || "#"
      })
    }))
  })
})}
```

is this the right approach on hyperHTML?

but i'm still puzzled by my previous code, i see nothing's wrong with it;  anyway should we mutate another component's state, how we gonna do that? simply sending CustomEvent to top level parent? also the best practices on building large scale & complex webapp in hyperHTML?
_(should i open new issue for this question?)_

**Comment by WebReflection** [comment]
Also this: https://github.com/WebReflection/hyperHTML/pull/202#issuecomment-368425690

So you never use (never **ever**) `new Anything` inside a template, because that's not going to do what you expect.

Relate the content of each component with their owner or the component context itself, and use full potentials of hyperHTML.Component.

```js
${Header.for(this).update({
  content: List.for(this).update({
    tag: "UL",
    class: "no-scrollbar",
    content: this.state.ofHeaderListItems.map((b, i) => ({
      content: Link.for(this, i).update({
        content: b.title || "#",
        click: e => this.menuClicked(e, b),
        class: b.url === this.state.route ? "active" : null,
        href: b.url || "#"
      })
    }))
  })
})}
```

Closing this since I am pretty sure there's nothing to do for me.
