### ISSUE TITLE
debugger in released code

### ISSUE THREAD

**Issue by sebd-davra** [WebReflection/hyperHTML#239]
Hi Andrea,

There is annoying debugger in released code : 
https://unpkg.com/hyperhtml@2.10.6/index.js
line 1175
Could you remove them please ?

Regards,

Sébastien

**Comment by WebReflection** [comment]
oh gosh .... sorry for that, the linter should've avoided that!

**Comment by WebReflection** [comment]
done

**Comment by sebd-davra** [comment]
still on https://cdn.jsdelivr.net/npm/hyperhtml@latest/index.js

**Comment by sebd-davra** [comment]
thanks
