### ISSUE TITLE
Animations?

### ISSUE THREAD

**Issue by ebremmer** [WebReflection/hyperHTML#24]
How to best deal with animations, ex. post render?

**Comment by WebReflection** [comment]
you invoke the `update` or `render`, instantly after would just do it?

**Comment by ebremmer** [comment]
it probably would but maintaining such code would be less then ideal, looking for some good construct wrap it nicely.

**Comment by WebReflection** [comment]
sorry, what?

**Comment by ebremmer** [comment]
would you care for good example then?

**Comment by WebReflection** [comment]
I don't even know your use case or how your code would look like, how can I possibly help?

**Comment by ebremmer** [comment]
Andrea, any example that would show how to deal with animations would be of help and am pretty sure would help others like me adopt this wonderful thing.

In my particular case I wonder how to trigger animation when content is rendered, imagine when you hit enter to add todo, your model state changes causing update, when new element shows up, what's the best way to trigger animation (node class list update).

**Comment by WebReflection** [comment]
I've changed one demo-test to use animations, if you mean CSS animations.

basically the CSS bit is
```css
    .fading {
      animation: fadein .600s ease-in;
    }
    @keyframes fadein {
      0% {
        opacity: 0;
      }
      100% {
        opacity: 1;
      }
    }
```

and the JS part is
```js
  function update() {
    render`
      Incremental updates for ${items.length} items
      <form onsubmit="${e => confirm('Are you sure ?')}">${
        items.map((item, i) => hyperHTML.wire(item)`
        <input class="fading" name="${'input-' + i}">`)
      }<input type="submit">
      </form>
    `;
  }
```

Since nodes already there won't ever change, unless you change the wire around them, there's really nothing special to do there.

Does this answer your question?

**Comment by WebReflection** [comment]
forgot the live demo:
https://webreflection.github.io/hyperHTML/test/incremental.html

**Comment by ebremmer** [comment]
You are right, my poor communication failed here, I was thinking about transitions and writing animations. 

I want to kick off transition by changing adding class.

**Comment by WebReflection** [comment]
use `<node class="${model.class}">` to do that?

**Comment by ebremmer** [comment]
it did help, thank you!
