### ISSUE TITLE
IE and MS Edge - Dispatch event for node.children doesn't work for SVG elements 

### ISSUE THREAD

**Issue by anthony-redFox** [WebReflection/hyperHTML#244]
https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children

Doesn't support SVG Elements in IE and MS Edge

https://github.com/WebReflection/hyperHTML/blob/26bf6d256a4a4089891cab0d8960f2f2cac98d5e/cjs/objects/Updates.js#L493

**Comment by WebReflection** [comment]
thanks, I should've fixed this on latest. Please let me know if that is not the case.
