### ISSUE TITLE
Firefox not updating

### ISSUE THREAD

**Issue by pinguxx** [WebReflection/hyperHTML#248]
Not sure what library has this problem but in chrome 67 this works fine

https://codepen.io/pinguxx/pen/wXYYdZ?editors=0011

But in firefox 61 it doesn't update or show anything, any idea?

**Comment by pinguxx** [comment]
Im loading document-register-element.js see the settings
https://cdnjs.cloudflare.com/ajax/libs/document-register-element/1.8.0/document-register-element.js

**Comment by WebReflection** [comment]
Will have a look but works everywhere for me.
https://mobile.twitter.com/WebReflection/status/1010471158301544448

**Comment by WebReflection** [comment]
Hi @pinguxx , sorry for not having a better look before but this was a bug of the polyfill, incapable of patching nodes imported via `document.importNode`.

Everything should work as expected now, but you need to use `1.10` or simply use the unpkg cdn: https://unpkg.com/document-register-element

**Comment by pinguxx** [comment]
sweet, thanks @WebReflection
