### ISSUE TITLE
ShadyDom / ShadyCss Support

### ISSUE THREAD

**Issue by snajo** [WebReflection/hyperHTML#258]
It would be nice to have built-in shadow dom / shady css support.
Do you already thought about?

**Comment by WebReflection** [comment]
You cannot represent ShadowDOM as HTML, can you?

**Comment by WebReflection** [comment]
P.S. [HyperHTMLELement](https://github.com/WebReflection/hyperHTML-Element#hyperhtml-element) can have shadow DOM so you can use it, and related polyfills, with it.

**Comment by WebReflection** [comment]
P.S.2 when it comes to polyfills, don't forget [attachshadow](https://github.com/WebReflection/attachshadow#attachshadow)

**Comment by snajo** [comment]
Hi, 

thanks for your fast feedback. You are right, HyperHTMLElement is maybe the better place to talk about. 

Currently if we create a shadow root and we bind hyper to the the shadow root, then we can use some methods from the shadycss/shadow dom polyfill to extract the css and attach it to documents head (<style scope="my-element"></style>). => https://github.com/webcomponents/shadycss/blob/master/README.md#example 

The template (we have to pass the rendering first through a template element and then to the shadow root) contains then something like that:
<div class="style-scope my-element"></div>

But if we re-render the template with hyper these classes are removed (because it`s not part of the template and manually added by the shadycss polyfill method). It would be nice if hyper can keep these classes. Do you know what i mean?

Sure, we can add these classes again with calling the shadycss polyfill method again. 
But i think this is from the point of performance not the best way.

Thanks
Thomas

**Comment by WebReflection** [comment]
This project does't care about 3rd parts libraries, only about Web standards, and indeed you can use anything you want as html, including Shadow DOM.

```js
class MyComponent extends HyperHTMLElement {
  created() {
    this.html = hyperHTML.bind(
      this.attachShadow({mode: 'closed'}) // or open
    );
  }
  render() {
    this.html`
    <style>
    :host {
      display: block;
    }
    #container slot::slotted(*) {
      color: gray;
    }
    #foo {
      color: black;
    }
    </style>
    <div id="foo">Shadow</div>
    <div id="container">
      <slot>
        <!-- span distributed here -->
      </slot>
    </div>
    <!-- /shadow-root -->
    <span>Light</span>`;
  }
}
```
