### ISSUE TITLE
Guidance on boolean attributes

### ISSUE THREAD

**Issue by marcos-travel** [WebReflection/hyperHTML#26]
There are attributes in HTML, like "hidden", which don't accept an attribute value. E.g.,:

```HTML
<div hidden>
```
 It's not clear to me how to deal with those - as they sometimes need to be included conditionally (cheap hack is to use `style=""` or a CSS class - but not as nice). 

So... wondering if you have any idea about how those can be included ... or if they might need to be a special case.

**Comment by WebReflection** [comment]
Boolean attributes are already supported but maybe hidden is missing? Can't check now but try via hidden=${true} and see how that goes (when you pass false it should drop the attribute)

**Comment by WebReflection** [comment]
Sorry, I meant hidden="${true}"

**Comment by marcos-travel** [comment]
```
I need hidden="${false}"
```

But doesn't seem to be working:

<img width="531" alt="screen shot 2017-03-24 at 12 30 00 pm" src="https://cloud.githubusercontent.com/assets/26573586/24306185/ae2b82f4-108d-11e7-9dae-6992c8845aaa.png">

**Comment by WebReflection** [comment]
It's not in the list of Boolean attributes within the RegExp but I can't do anything before Sunday cause hotels WiFi suck

**Comment by marcos-travel** [comment]
heh, np. No hurry, I'm also travelling this weekend.

**Comment by WebReflection** [comment]
latest version has `hidden` too. If you find other boolean attributes please let me know, thanks.

**Comment by marcos-travel** [comment]
Awesome! working beautifully.
