### ISSUE TITLE
Attributes splat

### ISSUE THREAD

**Issue by chanind** [WebReflection/hyperHTML#262]
In JSX it's common to have components that accept an open-ended list of props and apply those props as attributes. For example:

```javascript
<button onClick={() => console.log('clicked')} className="meh" {...props}>Generic Button</button>
```

Is there an equivalent way to pass an object into a hyper HTML element and have it turn the keys/values into attributes on the object? I tried the following but it doesn't seem to work:

```javascript
const extraProps = {'data-attr1': 'meh', class: 'awesome-button'};
wire()`<button ${extraProps} onClick=${() => console.log('clicked')}`>click me</button>`
```

**Comment by jfrazzano** [comment]
I had this working a while ago on non self closing tags.  I filtered to an alternative version for self closing;

function destructForStyle(o){
		return 	Object.keys(o).reduce((pre,key,i)=>{
		 				pre=pre.concat(`${key}`,":",`${o[key]};`);
		 					return pre;	
		 				},``)
		}
function destruct(o){
			return  `${Object.keys(o).reduce((pre,key,i)=>{
		 				pre=pre.concat(`${key}`,"=",`"${key!=="style"?o[key]:destructForStyle(o)}"`);
		 					return pre;	
		 				},"")}`;
		 }
	
String.prototype.tag=function(tag,properties){return `<${tag} ${properties}>${this.toString()}</${tag}>`;
                                                 };
//usage*** on any non self-closing tag
//let div=`somechildhtmlstring`.tag("div",destruct(divspropertiesobject))’;
wire()`${div}`;

**Comment by WebReflection** [comment]
this has been solved with definitions , you can read everything about this matter in here https://github.com/WebReflection/hyperHTML/issues/256#issuecomment-408601056
