### ISSUE TITLE
List items

### ISSUE THREAD

**Issue by rbiggs** [WebReflection/hyperHTML#27]
Nice framework. I've used straight template literals a lot. I love them. I've also used Yo-yo/Choo, Hyperx with Virtual Dom and Hyperapp. I'm not quite sure how to handle rendering repeating items from an array. I tried creating an example of composable parts, but can't seem to get the list items to render. They come back as strings, not what I was expecting. With normal template literals that would work. What am I doing wrong?

```js
const render = hyperHTML.bind(document.body)
const wire = hyperHTML.wire()

const fruits = ['Apples', 'Oranges', 'Bananas']

const header = render => render`
  <nav>
    <h1>The Title</h1>
  </nav>`;

const footer = render => render`
  <footer>
    <h3>The footer</h13>
  </footer>`

const main = render => render`
  <section>
    <h2>Fruits</h2>
    <ul>
      ${fruits.map(fruit => `<li>${fruit}</li>`).join('')}
    </ul>
  </section>`

const update = render => render`${[header(wire), main(wire), footer(wire)]}`
update(render)
```

**Comment by WebReflection** [comment]
You're putting spaces around. There are only 3 rules to remember, please read them.

**Comment by rbiggs** [comment]
Ah, you mean on the `ul`. 🤦‍♂️

**Comment by WebReflection** [comment]
Yes, and if you want safe text inside <li> put at least a space around. HTML and wires are opt in and the best compromise is to have no spaces around. It'd be impossible to have this behavior swapped but it worked for all simple-to-complex examples and demos.

**Comment by WebReflection** [comment]
Put a space around < li >

**Comment by WebReflection** [comment]
Sorry I can't answer through my phone any better at this time

**Comment by rbiggs** [comment]
No probs. Thanx a lot. Appreciate the quick response ;-)
