### ISSUE TITLE
Unmodified content rerendered when code is compiled with TypeScript to ES5

### ISSUE THREAD

**Issue by wlinna** [WebReflection/hyperHTML#270]
In short, hyperHTM doesn't work with TypeScript, because when code is compiled with TypeScript to ES5, unmodified content is rerendered. With Babel that doesn't happen.

I created a pen to demonstrate this issue:

https://codepen.io/anon/pen/oPoWXX?editors=0011

To see the issue, select TypeScript as a preprocessor (if it isn't already), start the video, and then press the button. The problem doesn't occur when using Babel as a preprocessor.

While I know this is a TypeScript problem (and you won't like seeing this issue here), I reported it here for two reasons:

- To let you know that this problem still exists, even after efforts to fix / workaround the the problem
- I don't know how to show that this is a TypeScript problem. I tried to understand the issue myself first*, but I'm unable to comprehend this problem fully (or more specifically, the attempted fix in TypeScript).

I know that you attempted to workaround the issue, but I don't know if it is present in hyperHTML v2, or if it ever covered this issue (completely).

It might be worth mentioning in the documentation, that using TypeScript with ES5 output is problematic, even if the problem is on the TypeScript side.

*I read https://github.com/Microsoft/TypeScript/issues/17956, https://github.com/WebReflection/hyperHTML/pull/101, https://github.com/Microsoft/TypeScript/pull/18300 and some of your blog-posts

**Comment by WebReflection** [comment]
This is your issue in a nutshell: TypeScript does not transpile ES6 string literals in a standard way.

Literally nothing I can do with this, and lit-html has the same exact issue.

Please talk to TypeScript chaps or ask CodePen if they are embedding an updated version of TypeScript.

```js
var invokes = [];
function test(template) {
  invokes.push(template); 
}

function update(value) {
  test`some ${value}!`;
}

update(1);
update(2);

document.body.textContent = invokes[0] === invokes[1];
```

**Comment by WebReflection** [comment]
FYI I've fixed with yet another workaround TypeScript shenanigans hoping they will stop breaking standards behavior.

As soon as [unpkg/hyperhtml](https://unpkg.com/hyperhtml@latest) returns version `2.13.1` your code pen should work just fine even in TypeScript.

**Comment by wlinna** [comment]
Thank you very much. You were quicker than I anticipated, and you even came up with a workaround. The pen works correctly now.

I'm going to bring this up at TypeScript's issue tracker in the near future.
