### ISSUE TITLE
[question] Late binding, and use with icomponent

### ISSUE THREAD

**Issue by prasannavl** [WebReflection/hyperHTML#290]
Hi,  I'm currently writing a render agnostic component here: https://github.com/prasannavl/icomponent

The idea is that it provides lifecycle and explicit render control, while abstracting the rendering methods. I've been meaning to provide some hyperhtml examples,  but have not been able to land on a satisfactory one yet. Currently I can use it with hyperhtml, with this:

```js
import { IComponent } from "icomponent/lib";
import { wire, bind } from "hyperhtml";

class App extends IComponent {
  constructor() {
    super();
    this.html = bind(this.getRenderRoot());
  }

  _render() {}

  view() {
    return this.html`
          <section>
            Hello
          </section>
        `;
  }
}
```

But I'm not entirely happy with this, since it binds the renderRoot early, and also doesn't keep the view function a pure one, with an empty render.

For instance, here's an example with lithtml: 

```js
import { html, render } from "lit-html";
import { IComponent } from "icomponent";

class App extends IComponent {
 _render() {
      render(this.view(), this.getRenderRoot());
 }

  view() {
        return html`
        <div>Hello world!</div>
        `;
    }
}

customElements.define("x-app", App);

``` 

Here view is a pure fn, and render does the work, is the model I'm trying to provide for all renderers.

Most of the examples in my README also uses `lit-html` currently (by setting the render fn globally via `IConfig.render`).  I'd love to provide some examples with `hyperhtml` instead. Eventually my goal is to encapsulate it into it's own `HyperComponent`, and provide them as a separate package. So, you can use mix and match all sorts of components on one application retaining the same render agnostic model. I was hoping you can point me in the right direction to accomplish this the best way for  `hyperhtml`.

Thanks! :)

**Comment by WebReflection** [comment]
so, with hyperHTML you have no external dependencies but you call a pure function the one with external dependencies and also logic? Not sure I am following.

Anyway, would this option work ?

```js
class App extends IComponent {
  get html() {
    return this._html || (this._html = bind(this.getRenderRoot()));
  }
  _render() {}
  view() {
    return this.html`
      <div>Hello world!</div>
    `;
  }
}
```

Or you can simply use `hyperHTML.Component` which works out of the box. 👋

**Comment by WebReflection** [comment]
P.S. what I meant, is that the moment you need a `_render` with a proper context, your purity in `view()` becomes meaningless

**Comment by prasannavl** [comment]
@WebReflection - By pure function, I mean a function without any side effects. What you just wrote is similar to the one the I had used (except you moved it to a property) :) 

So, basically, `view` can do whatever, just no have side effects or do the actual rendering in the DOM. The idea is to provide the representation, the effects of which happen in `render`.

Or, simply put, calling `view` multiple times, should have no impact. But here, calling view DOES the actual render.

**Comment by WebReflection** [comment]
what about this?

```js
const html = (...args) => args;

class App extends IComponent {
  _render() {
    bind(this.getRenderRoot())(...this.view());
  }
  view() {
    return html`
      <div>Hello world!</div>
    `;
  }
}
```

hyperHTML is based on functions itself, you can play around as much as you like with those.

**Comment by prasannavl** [comment]
Ah, I thought `bind` was some expensive function that's used to bind the DOM, but looks like it's just a simple javascript bind. Reverting to your code, as the above provides no gain whatsoever.

**Comment by WebReflection** [comment]
Yup, bind is pretty much, exactly, the function prototype bind 😉

**Comment by prasannavl** [comment]
All done! Thanks!
