### ISSUE TITLE
Organisation for hyperhtml

### ISSUE THREAD

**Issue by ematipico** [WebReflection/hyperHTML#303]
Have you thought creating an organisation to include all your repos regarding all hyperhtml-style ecosystem? (Viperhtml, hyperhtml-style), etc.

**Comment by WebReflection** [comment]
Last time I did it required a lot of effort and brought in **zero** new contributors so no

**Comment by WebReflection** [comment]
P.S. [viperHTML](https://github.com/viperHTML) is already an organization, demonstrating creating one never changed a thing :-(
