### ISSUE TITLE
How to move childnodes of custom elements? Like slot's

### ISSUE THREAD

**Issue by AndyOGo** [WebReflection/hyperHTML#310]
I'm curious if [`<slot>`](https://html.spec.whatwg.org/multipage/scripting.html#the-slot-element)'s or similar functionality to React/JSX [`children`](https://reactjs.org/docs/jsx-in-depth.html#children-in-jsx) is supported?

Like this example of `<custom-element>`, which has:

The following `children` (**light DOM**):

```html
<custom-element>
  <span>This is some light DOM for custom-element</span>
</custom-element>
```

need to be properly slotted/injected into it's **local DOM** like:

```html
<div>
  ${children} <!-- light DOM injection point -->
</div>`;
```

producing the following **flatted DOM**:

```html
<custom-element>
  <div>
    <span>This is some light DOM for custom-element</span> <!-- light DOM injection point -->
  </div>
</custom-element>
```

**Comment by WebReflection** [comment]
slots are usually handled by custom elements and Shadow DOM, nothing different in hyperHTML, right?

**Comment by AndyOGo** [comment]
Indeed, if the browser supports it though.

I'm more curious about `children` in general, if they work and if they get properly diffed incrementally?
