### ISSUE TITLE
create-content seems included twice

### ISSUE THREAD

**Issue by brunoscopelliti** [WebReflection/hyperHTML#315]
In the current [latest version](https://cdn.jsdelivr.net/npm/hyperhtml@2.22.1/index.js), _@ungap/create-content_ seems to be included twice.

To verify, open previous link, and search for `var createContent`; you'll find matches for `var createContent` and `var createContent$1`, but the code is almost identical. Is this expected?

**Comment by WebReflection** [comment]
it looks like a rollup plugin issue https://stackoverflow.com/questions/53302600/rollup-babel-duplicate-definitions-in-output-file

**Comment by brunoscopelliti** [comment]
Does your previous commit fix the issue with rollup, or we've to wait for a fix on rollup itself?
