### ISSUE TITLE
ref attribute support

### ISSUE THREAD

**Issue by ikabirov** [WebReflection/hyperHTML#318]
Is it planned? It will be very useful with useRef() hook implementation:

```function TextInputWithFocusButton() {
  const inputEl = useRef(null);
  const onButtonClick = () => {
    // `current` points to the mounted text input element
    inputEl.current.focus();
  };
  return (
    <>
      <input ref={inputEl} type="text" />
      <button onClick={onButtonClick}>Focus the input</button>
    </>
  );
}
```
It seems the best solution for that case

**Comment by yuretz** [comment]
Yu can easily do it without any additional attributes:
```javascript
const {bind, wire} = hyperHTML;
const inputEl = wire()`<input type="text" />`;
const onButtonClick = () => {
  // `inputEl` is just an input element node :)
  inputEl.focus();
};

bind(document.body)`
  ${inputEl}
  <button onclick=${onButtonClick}>Focus the input</button>
  `;
```

**Comment by joshgillies** [comment]
You don't really need `ref` in hyperHTML, namely because hyperHTML uses The Platform™️ you already have APIs for direct access to any element you like. As with @yuretz example, sure you can create a wire that contains the reference the the DOM node you're interested in, but alternatively you can also query the DOM directly with `document.querySelector` et al.

**Comment by ikabirov** [comment]
>You can easily do it without any additional attributes:
I want do it without additional render function. It's allow to see all html in one place.

>  you can also query the DOM directly with document.querySelector et al.
Too much pain with refactoring. Id's should be unique in DOM, selectors and nesting are unstable and can be easily changed with redesign.

**Comment by yuretz** [comment]
Take a look [at this](https://jsfiddle.net/yuretz/w7mh1znj/). Isn't it exactly what you want?

**Comment by ikabirov** [comment]
@yuretz Exactly! Thanks you

**Comment by yuretz** [comment]
Oh yeah, and it works with the `useRef()`, provided by neverland too, I've just haven't noticed it's already there, so I implemented my very own one, and there was no need for that.
You are welcome!
