### ISSUE TITLE
passive events support

### ISSUE THREAD

**Issue by ikabirov** [WebReflection/hyperHTML#321]
Is it possible to use passive for scroll/touchstart events? 
Now we have chrome violation: ```[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952```

**Comment by yuretz** [comment]
You could always do it in non-declarative way of course, by using node references returned by `wire()` or via `document.querySelectorAll()`.
If you want to do it declaratively, you could probably use `define()` to create a custom attribute intent where you would pass an event handler and call your `element.addEventListener(..., {passive:true})` from inside the intent callback. But in this case I'm not sure where would you call the `removeEventListener()` from... Maybe @WebReflection could shed some light on what would be the proper way of implementing it, once he's back from holiday?

**Comment by yuretz** [comment]
If there was an optional, second clean-up callback parameter in the `define()`, that would have been a good place to remove the event listeners added in the first one...

**Comment by ikabirov** [comment]
Use passive events by default looks like a good idea. It's good for application performance. But original html events attributes always non passive. 
Anyway, let's wait for @WebReflection

**Comment by WebReflection** [comment]
passive by default is not an option because that is not the HTML default (least surprise), but the hint about the intent sounds reasonable to me:

```js
hyperHTML.define(
  'passive-events',
  (node, info) => {
    for (var key in info) {
      if (key.slice(0, 2) === 'on') {
        var method = info[key] ? 'add' : 'remove';
        node[method + 'EventListener'](key.slice(2), info[key], {passive: true});
      }
    }
    return '';
  }
);
```

With that, you can have:

```js
html`<div passive-events=${{
  ontouchstart: callbackOrContextOrNull,
  onscroll: callbackOrContextOrNull
}} />`
```

that makes configuration of events pretty trivial, as long as callbacks/context/values are not generated at runtime, otherwise you need a WeakMap to relate the node, and store previous values there and do the `add/remove` dance only when previous values are different.

I hope you got the idea.

**Comment by ikabirov** [comment]
```
  var method = info[key] ? 'add' : 'remove';
  node[method + 'EventListener'](key.slice(2), info[key], {passive: true});
```

its doesn't work. When remove we must have old function reference, not null. 
> I hope you got the idea.

yep, thanks!

**Comment by WebReflection** [comment]
you are right, then it's a bit more complicated, but not too much.

```js
const wm = new WeakMap;
hyperHTML.define(
  'passive-events',
  (node, info) => {
    const saved = wm.get(node) || wm.set(node, {}).get(node);
    for (var key in info) {
      if (key.slice(0, 2) === 'on') {
        var diff = saved[key] !== info[key];
        if (diff) {
          var type = key.slice(2);
          var options = {passive: true};
          if (saved[key])
            node.removeEventListener(type, saved[key], options);
          saved[key] = info[key];
          if (saved[key])
            node.addEventListener(type, saved[key], options);
        }
      }
    }
    return '';
  }
);
```

**Comment by ikabirov** [comment]
this works for me:
```
const passiveListenersMap = new WeakMap();

/**
 * @param {Element} node
 * @param {?} info
 */
function passiveEventHandler(node, info) {
	const oldInfo = passiveListenersMap.has(node)
		? passiveListenersMap.get(node)
		: {};

	for (const key of Object.keys(info)) {
		if ((key.slice(0, 2) === 'on') && oldInfo[key] != info[key])
		{
			const eventType = key.slice(2);
			if (oldInfo[key])
			{
				node.removeEventListener(eventType, oldInfo[key]);
			}
			if (info[key])
			{
				node.addEventListener(eventType, info[key], {passive: true});
			}
		}
	}
	passiveListenersMap.set(node, info);
	return '';
}
hyperHTML.define(
	'passive-events',
	passiveEventHandler,
);
```

**Comment by ikabirov** [comment]
got it!
