### ISSUE TITLE
Incorrect sample from documentation

### ISSUE THREAD

**Issue by ikabirov** [WebReflection/hyperHTML#341]
Sample from https://viperhtml.js.org/hyperhtml/documentation/#essentials-3 doesn't work correctly, cause it different template literals

playground: https://codepen.io/ikabirov/pen/MLGNPV

**Comment by WebReflection** [comment]
That changed [after this ECMAScript change](https://itnext.io/a-tiny-disastrous-ecmascript-change-fadc05c83e69), the example now should be:

```js
const info = {some: 'data'};

const view = info => hyperHTML.wire(info)`
                      <li></li>`;

const sameLI = view(info);
 
// what if we use same template later on?
console.assert(
  sameLI === view(info),
  'same reference means exactly the same node'
);
```

However, this is not the right repository 👋
