### ISSUE TITLE
wire(obj)`<li></li>` !== wire(obj)`<li></li>`

### ISSUE THREAD

**Issue by BlueWater86** [WebReflection/hyperHTML#350]
Hi Andrea, one of the examples given regarding wires producing the same node is no longer working as expected. I would have taken a look at the cause but our current sprint doesn't give me any free time.

https://codepen.io/bluewater86/pen/zbJagB

```
const info = {some: 'data'},
      a = hyperHTML.wire(info)`<li></li>`,
      b = hyperHTML.wire(info)`<li></li>`
console.assert(a === b, 'same reference means exactly the same node');
```

**Comment by WebReflection** [comment]
It's explained in here: https://medium.com/@WebReflection/a-tiny-disastrous-ecmascript-change-fadc05c83e69

this would work

```js
const li = info => hyperHTML.wire(info)`<li></li>`;
const info = {some: 'data'},
      a = li(info),
      b = li(info);
console.assert(a === b, 'same reference means exactly the same node');
```

**Comment by BlueWater86** [comment]
Thanks for the info; crazy how the treatment of the standard changed like that. The 'same reference means exactly same node' example is still in your documentation which was confusing.
![image](https://user-images.githubusercontent.com/6543901/54798811-18734380-4ca6-11e9-9e80-af79c67662e5.png)
