### ISSUE TITLE
unquoted attributes with / crash

### ISSUE THREAD

**Issue by atirip** [WebReflection/hyperHTML#359]
https://codepen.io/anon/pen/EJqMXO?editors=0011

This throws:

       var a = 'go';
       hyperHTML.wire()`<link rel=stylesheet type=text/css href=${a}>`;

Adding quotes around (`type="text/css"`) works.

**Comment by WebReflection** [comment]
that's how standard works

**Comment by atirip** [comment]
https://validator.w3.org/nu/#textarea says: Document checking completed. No errors or warnings to show.

`<!doctype html><html lang=en><title>document</title><link rel=stylesheet type=text/css href=foo.css><p>hello world!`

**Comment by WebReflection** [comment]
fair enough, I thought slashes were not possible. However, this is a [domtagger](https://github.com/WebReflection/domtagger) issue, not an hyperHTML one.

**Comment by WebReflection** [comment]
OK, this has been solved all over the place (including lighterhtml)

Thanks for filing the bug 👋
