### ISSUE TITLE
onconnecetd fires twice

### ISSUE THREAD

**Issue by atirip** [WebReflection/hyperHTML#363]
I have a hard time to understand why bind inside bind fires onconnected events twice. 

https://codepen.io/anon/pen/YbaGqw?editors=0011

This is just extracted principle from bigger codebase and while I can easily rewrite this example, I realistically can not or want to change the approach in whole.

**Comment by WebReflection** [comment]
this bug is probably related to _disconnected_ helper, but thanks for filing it, it's a good bug, with a reduced example.

**Comment by WebReflection** [comment]
as you can see by using `https://unpkg.com/hyperhtml@latest` this bug has been fixed 🎉

**Comment by atirip** [comment]
That is impressive. Thanks.
