### ISSUE TITLE
MS EDGE text node x attribute issue

### ISSUE THREAD

**Issue by Beppe** [WebReflection/hyperHTML#377]
EDGE (Microsoft EdgeHTML 18.18362):
```
document.body.appendChild(hyperHTML.wire(null,'svg')`	
<svg><text x="10" y=${30}>ciao</text>	
</svg>`);
```
All as expected

```
document.body.appendChild(hyperHTML.wire(null,'svg')`	
<svg><text x=${100} y="30">ciao</text>	
</svg>`);

```
console:
```
SCRIPT5022: SCRIPT5022: 1 values instead of 0	
<svg><text x=${value} y="30">ciao</text>	
</svg>
```

On EDGE beta (Version 78.0.276.19 (Official build) beta (64-bit)) eveything is OK

**Comment by Beppe** [comment]
(workaround):
```
document.body.appendChild(hyperHTML.wire(null,'svg')`	
<svg><text transform=${`translate(${100} ${30})`}>ciao</text>	
</svg>`);
```

**Comment by WebReflection** [comment]
> On EDGE beta (Version 78.0.276.19 (Official build) beta (64-bit)) eveything is OK

Edge already has gazillion issues with attributes ... I'm glad to know they solved this in latest, hoping that's already the Chromium one.

Since there is a work around, I'm not sure I should waste time solving this, but I'll keep this open for now, and thanks for filing this bug 👍

**Comment by WebReflection** [comment]
@Beppe you should try this with latest _hyperHTML_

```js
document.body.appendChild(hyperHTML.wire(null,'svg')`	
<svg><text x="10" .y=${30}>ciao</text>	
</svg>`);
```

Using attribute setters never fails in both old Edge and IE 👋
