### ISSUE TITLE
offsetWidth and offseHeight return 0

### ISSUE THREAD

**Issue by mqxim** [WebReflection/hyperHTML#384]
Hello, now i`m working on the project which uses hyperHTML,
I'm trying to get offsetWidth and offsetHeight of the element but it always returns 0, could you help me please, what am i doing wrong?

```
    public created(): void {
        this.render();

        console.log(this.offsetWidth,this.offsetHeight); // always 0 0
    }
```

I am using HyperHTMLElement with typescript
How can i get element width and height?

**Comment by WebReflection** [comment]
as I've no idea what your `render()` contains, I've also no idea how to answer your question.

Moreover, I don't understand the use case, so there's [room for improvements in this issue](https://gist.github.com/WebReflection/f6dc8017a1c10f0ece2e292b0b9607ff).

**Comment by WebReflection** [comment]
Closing until there is something to test.
