### ISSUE TITLE
"original.cloneNode is not a function" using hyperhtml with basichtml

### ISSUE THREAD

**Issue by Golmote** [WebReflection/hyperHTML#400]
Hello,

I'm encountering an error that seems quite similar to the one described in #190, except I'm using basichtml.

Below is the Minimal, Reproducible Example I could come up with. Am I doing something wrong that I can't see?

```js
import {Document} from "basichtml";
import hyper from "hyperhtml";

it('should work', () => {
    global.window = global;
    global.document = new Document();

    const root = document.createElement('div');
    const cls = 'foo';

    // This test passes
    expect(() => {
        hyper(root)`<div class="foo"></div>`;
    }).not.toThrow();

    // This test fails
    // TypeError: original.cloneNode is not a function
    // Tagger.attribute (node_modules/hyperhtml/cjs/objects/Updates.js:176:34)
    expect(() => {
        hyper(root)`<div class=${cls}></div>`;
    }).not.toThrow();
});
```

(I run that test using Jest. hyperhtml and basichtml are both in their latest versions, 2.32.2 and 2.3.0, respectively.)

**Comment by WebReflection** [comment]
the whole library is tested via `basicHTML` https://github.com/WebReflection/hyperHTML/blob/master/test/test.js and I've just tried this on top:

```js
const root = document.createElement('div');
const cls = 'foo';
console.log(hyperHTML(root)`<div class="foo"></div>` === root);
console.log(hyperHTML(root)`<div class=${cls}></div>` === root);
```

it works without issues.

**Comment by Golmote** [comment]
After more digging, TIL that Jest runs the tests in a jsdom environment by default...

So if anyone runs into this issue, the fix seems to be setting [Jest's `testEnvironment` to `"node"`](https://jestjs.io/docs/en/configuration#testenvironment-string).

Thank you for your time!
