### ISSUE TITLE
README, dedicated forum and collective

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/hyperHTML#407]
hyperHTML is always in my heart.

In the README:

- Change https://webreflection.boards.net/ with https://github.com/WebReflection/discussions/discussions
- Sponsor this project: opencollective.com/hyperHTML - broken link
- (review viper site to extract hyperHTML docs)

Thanks for your effort.

**Comment by WebReflection** [comment]
thank you ... but what's wrong with a PR? 😅 ... will update/check this as soon as I find some time 👍

**Comment by WebReflection** [comment]
Uhm ... second point should be [addressed here](https://github.com/WebReflection/donate) (I will, as soon as I can) while the third one, I am not super sure what's that about 🤔

**Comment by WebReflection** [comment]
> it seems weird that is contained in a deprecated project.

does it matter though? hyperHTML is pretty much done, and the whole family has been replaced by uhtml and friends. The domain was gently offered by js.org, not sure it’s worth chaining it?
