### ISSUE TITLE
Events problem

### ISSUE THREAD

**Issue by jbremmer** [WebReflection/hyperHTML#41]
```
onclick="${function withName() { console.log('whatev'); }}"
```

produces: `SyntaxError: expected expression, got '}'`

and markup:

```
<div onclick="function withName(){console.log(" blah")}"="" >
  </div>
```
Not sure what am I doing wrong.

**Comment by WebReflection** [comment]
Neither am I
Where is the code?
That's not even a template literal.
Where is the tag?
Can you file a bug that gives me **as many info** as possible instead of a copied pasted extract of your code?

Thank you
