### ISSUE TITLE
Binding multiple elements

### ISSUE THREAD

**Issue by BentleyDavis** [WebReflection/hyperHTML#44]
I will be using HyperHTML to create widgets on a web page within a content management system. I believe I will need to hyperHTML.bind multiple HTML elements. I will be adjusting you code to allow this but I wanted to see if you had any preferences on how to do it.
```
//Find all the statements in the document
var statements = document.getElementsByTagName('statement');

//Render the statements
for (let s of statements) {
    var render = hyperHTML.bind(s);
    update(render, dict, mainId, events);
}
```
https://github.com/BentleyDavis/ReasonRoot/tree/1fbec6a5327decdf78dedba80c2c63ed9625e0f2

**Comment by BentleyDavis** [comment]
I got it working without modifying your code. Still learning.

**Comment by WebReflection** [comment]
Not bad, but I've commented few things out of the main function.

```js
function renderNode(claim, parent) {

    // so far, a wire accepts only one argument
    // passing parent too is misleading
    var wire = hyperHTML.wire(claim);

    // don't be shy with indentation
    // gzip makes white spaces weight irrelevant
    var li = wire`
    <li class="${"rr_li " + (parent && parent.open ? 'open' : 'closed')}">
        <div class="claimBox">
            <span
                onclick="${events.open.bind(claim)}" 
                class="${"toggleButton " + (claim.open ? 'toggleButtonOpen' : 'toggleButtonClosed')}">
                ${/* this is #TEXT, spaces around*/claim.children.length > 0 ? '➤' : ''}
            </span>
            <input oninput="${events.updated.bind(claim)}" >
            ${claim.description}
        </div>
        <ul class="rr_ul">${claim.children.map(
            nodeId => renderNode(dict[nodeId], claim)
        )}</ul>
    </li>`;

    if (!wire.default) {
        wire.default = claim.description;
        li.querySelector('input').value = claim.description;
    }

    return li;
}```

**Comment by jfrazzano** [comment]
> On May 9, 2017, at 4:42 AM, Andrea Giammarchi <notifications@github.com> wrote:
> 
> Not bad, but I've commented few things out of the main function.
> 
> function renderNode(claim, parent) {
> 
>     // so far, a wire accepts only one argument
>     // passing parent too is misleading
>     var wire = hyperHTML.wire(claim);
> 
>     // don't be shy with indentation
>     // gzip makes white spaces weight irrelevant
>     var li = wire`
>     <li class="${"rr_li " + (parent && parent.open ? 'open' : 'closed')}">
>         <div class="claimBox">
>             <span
>                 onclick="${events.open.bind(claim)}" 
>                 class="${"toggleButton " + (claim.open ? 'toggleButtonOpen' : 'toggleButtonClosed')}">
>                 ${/* this is #TEXT, spaces around*/claim.children.length > 0 ? '➤' : ''}
>             </span>
>             <input oninput="${events.updated.bind(claim)}" >
>             ${claim.description}
>         </div>
>         <ul class="rr_ul">${claim.children.map(
>             nodeId => renderNode(dict[nodeId], claim)
>         )}</ul>
>     </li>`;
> 
>     if (!wire.default) {
>         wire.default = claim.description;
>         li.querySelector('input').value = claim.description;
>     }
> 
>     return li;
> }```
It’s a dropdown/widget that has selections/description/nest of sam/arrow forward if none or above?  

looks like a much smarter version of what i been trying passing only data in; Would love a bin or w/e.  Sorry to interject if you guys are deep in work.

**Comment by WebReflection** [comment]
I think you can play around in here: https://github.com/BentleyDavis/ReasonRoot

**Comment by jfrazzano** [comment]
awesome thanks will clone
.

**Comment by BentleyDavis** [comment]
@jfrazzano Definitely clone. It will be changing a lot soon tough into something quite different. To see what the final product will look like you can see the video at https://settleit.org/root
