### ISSUE TITLE
known issues with shadow-dom?

### ISSUE THREAD

**Issue by moebiusmania** [WebReflection/hyperHTML#46]
hi, I'm trying to use HyperHTML with vanilla custom elements using shadow dom, so far almost everything works fine except an issue when trying to re-render an attribute on tag on webcomponent property change... it works on Firefox (which is using the shadow dom polyfill) but does not work on Chrome (with the native implementation).

I will give you an example repo ASAP, but at the moment I would like to known if you are aware of any issue with shadow-dom or web components in general.

thanks

**Comment by WebReflection** [comment]
Nope

**Comment by joshgillies** [comment]
Hey @moebiusmania, did you reference the Custom Element examples in the repo already:

https://github.com/WebReflection/hyperHTML/blob/master/test/my-button.js#L3

If so, it would be good to get an example of what you're trying to do so we can debug from there. 👍

**Comment by moebiusmania** [comment]
@joshgillies didnt see that example, seems very useful! yes I'm already preparing a repo example for my issue, I will give you later in the morning. thanks!

**Comment by moebiusmania** [comment]
@joshgillies @WebReflection ok thanks to that file I've solved my problem, I was trying to use the ```wire``` method but I dint' get it right, I will check all of the examples to better learn it :)

thanks for this great work and your small assistance! (*BTW: my repo is https://github.com/moebiusmania/webcomponents-hyperhtml , I was having issue with the if-data component*)

**Comment by WebReflection** [comment]
watch out that your style will be wiped out here:
https://github.com/moebiusmania/webcomponents-hyperhtml/blob/master/src/components/tick-element.js#L22

Just drop this line: https://github.com/moebiusmania/webcomponents-hyperhtml/blob/master/src/components/tick-element.js#L13

And put styles in the render.
Don't worry, the element wont' be touched on any consecutive call, only this partial text node insde the LI element will change with new info:
https://github.com/moebiusmania/webcomponents-hyperhtml/blob/master/src/components/tick-element.js#L30


Also watch out here: https://github.com/moebiusmania/webcomponents-hyperhtml/blob/master/src/components/repeat-data.js#L41

This `<li>${e.body}</li>` is vulnerable to HTML injection, if not desired write `<li> ${e.body} </li>` instead.

On top of that, those nodes will be re-rendered each time, it's a perfect case for a wire with a reference.

```js
_renderData(data){
    console.log(data);
      this.data = data;
      this.root`
        <ul>${
          // still put spaces around ${e.body} if it's text
          this.data.map(e => hyperHTML.wire(e)`<li>${e.body}</li>`)
        }</ul>
      `
  }
```
