### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for '_hyper_html: ' in null

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/hyperHTML#47]
(hyperhtml@0.11.0:15)

For a typo, I passed a `null` to the `bind` method and I got the error in the title when the template was rendered.

```
        const el = document.querySelector("foos"); // the tag is foo
        const render = hyperHTML.bind(el);
```

Does it make sense checking at least for a truthy value, not, of course, checking the existence, for not doubling the query call? 

I don't know if a default binding to the `document.body` may help.

**Comment by WebReflection** [comment]
> Does it make sense checking at least for a truthy value ?

there's literally nothing hyperHTML can do and `hyperHTML.bind(anything)` is exactly the equivalent of `anyFunction.bind(anything)`.

I am not willing to change native `Function.prototype.bind` and throwing at distance or erroring anyhow would produce the same result: your app is broken.

Don't bind non-existent nodes seems to be the best solution for everyone.

You had an early error, you fixed it early too.

**Comment by albertosantini** [comment]
Agreed.

Anyway my concern was about the cryptic error message, because the reason is in the bind, but the effect is in the render call.

The stack backtrace doesn't help to understand what is `null` and the first thought is some `null` in the template, because the offending line is "render`...".

Anyway this is the advantage to play with a micro lib: quickly you see what is wrong.

**Comment by WebReflection** [comment]
my concern is that for a case that is broken anyway, you want me to either overload the native `bind` with possible side effects through `fn.bind.call(hyperHTML, null)` or to make a check that would probably deoptimize execution.

Plus, your fallback to `documet.body` idea would create a whole new mess if two `hyperHTML` calls with bound `undefined` in different code are passed along.

At the end of the day, if you look carefully, the error is not too cryptic:

> Cannot use 'in' operator to search for '_hyper_html: ' in **null**

Knowing it as an error that happens with unintended binds would help more than a silent failure that fallbacks to any other random element.

As summary, I will think about it but I don't think I should fix this.

**Comment by albertosantini** [comment]
It seems I have been collecting a few `Uncaught TypeError`s. :)

Maybe, later, we may consider to create a sort of common errors section in the docs.
As I said in another issue, maybe it is enough this issue.

**Comment by WebReflection** [comment]
I'd love to have a section with most frequently errors so I can create documentation on how to avoid them.

Selecting the wrong node and behaving like jQuery, swallowing potentially entire applications, shouldn't belong to this library core :wink:

However, if there are obvious common error that can have a better outcome without compromising performance I'll be happy to improve there.

**Comment by WebReflection** [comment]
Last thought on this specific case, you could instead do this:

```js
const el = document.querySelector("foos"); // the tag is foo
const render = el ? hyperHTML.bind(el) : console.error;
```

But I'm sure that what you really want to do is to be sure your selectors have no typos 😛

**Comment by albertosantini** [comment]
I like this kind of early check. Thanks a lot.

Indeed checking the selectors would be perfect, but as I said `not, of course, checking the existence, for not doubling the query call`. :)
