### ISSUE TITLE
Web Components slots implementation

### ISSUE THREAD

**Issue by GianlucaGuarini** [WebReflection/hyperHTML#55]
Would it be possible to enhance a hyperHTML template in runtime using for example Web Components slots?
To be clear consider this example:
```js
// my-component.js
function create(root, state) {
  const render = hyperHTML.bind(root)
  // initial render
  template(render, state) 
  return {
    update(state) { 
      template(render, state) 
    }
  }
}

function template(render, state) {
  render`
    <div>
      <slot from="header"></slot>
      <h2>It is me ${state.name}.</h2>
      <slot from="footer"></slot>
    </div>
  `;
}
```
```js
// app.js
const app = create(document.querySelector('.app'), { name: 'Gian', role: 'dude', age: 84})

setTimeout(() => {
  app.update({ name: 'John', role: 'drugo', age: 77})
}, 2000)
```

```html
<!-- index.html -->
<div class='app'>
  <slot to='header'>
    <h1>My age is: ${ data.age }</h1>
  </slot>
  <slot to='footer'>
    <h3>My role is: ${ data.role }</h3>
  </slot>
</div>
```

I am trying to implement hyperHTML in riot.js but I am not able to cover this behavior in a clean way so any hint would be really appreciated.
Thank you

**Comment by WebReflection** [comment]
I think the example code is broken but I'd like to understand why would you need slots at all? Anyway, there is no DOM parsing in hyperHTML, only tree walking. If the slot element has a special meaning, it should just work as expected.

What am I missing?

**Comment by GianlucaGuarini** [comment]
> I think the example code is broken but I'd like to understand why would you need slots at all? 

I am sorry I have updated the previous example.

> Anyway, there is no DOM parsing in hyperHTML, only tree walking. If the slot element has a special meaning, it should just work as expected.
What am I missing?

Let's forget about the slots for now... I have tried to make a simpler example in order to know whether hyperHTML may handle a template provided in [this way](http://plnkr.co/edit/psULMj8IfwZZB0vb0RbP?p=preview)

**Comment by GianlucaGuarini** [comment]
I mean there is a [way to do it](http://plnkr.co/edit/v3eFIrjpRd946GOGRwPU?p=preview) but it needs `eval` and it's pretty dirty.

**Comment by GianlucaGuarini** [comment]
Ok nevermind, even Vue.js needs to rely on `Function` to [evaluate template strings in runtime](https://github.com/vuejs/vue/blob/07a37264c3b56952435331983adcf4081390b400/dist/vue.js#L9291) :shit: 

This is definitely not a problem that should be solved in hyperHTML.. thanks anyway and I am sorry for this waste of time

**Comment by WebReflection** [comment]
> even Vue.js needs to rely on Function

template literals are statics, you cannot create them at runtime through code, you need a transformer upfront.

Not sure what Vue had to do with it, since AFAIK Vue has nothing to do with template literals behaviors, it just parses strings, which is **not** what hyperHTML ot viperHTML does, which is taking advantage of the fact template literals are unique, being static.

**Comment by WebReflection** [comment]
FYI as you can see in the [comparison with Polymer](https://viperhtml.js.org/hyperhtml/examples/#!fw=Polymer&example=Compose%20with%20shadow%20DOM) slots work already out of the box in `hyperHTML` and also the recently introduced [HyperHTMLElement](https://github.com/WebReflection/hyperHTML-Element)
