### ISSUE TITLE
DOM lifecycle events

### ISSUE THREAD

**Issue by GianlucaGuarini** [WebReflection/hyperHTML#56]
At moment hyperHTML creates, updates and removes DOM nodes internally without providing any event hook. @WebReflection would you accept pull requests PR where the events above will be dispatched as custom events?
For example
```js
// updates
function update() {
    for (var
      i = 1,
      length = arguments.length,
      updates = this[EXPANDO].u;
      i < length; i++
    ) {
      updates[i - 1](arguments[i]);
    }
    this.dispatchEvent(new Event('updated'))
    return this;
}

// removes
node.removeChild(child);
walk(child, function(subChild) {
  if (subChild.nodeType === Node.ELEMENT_NODE) {
    subChild.dispatchEvent(new Event('removed'))
  }
})
```

**Comment by WebReflection** [comment]
nope, that's the Ember way and you know everything about ember perf issues.

You have to explain me at least two things here:

  1. why would you need at all to be notified about changes when you are the one causing them passing data through so you know already when these will happen
  2. why do you think MutationObserver is not the best solution for this task, which is exactly what MutationObserver was brought to the Web

hyperHTML needs a bound DOM node, and that's going to be a perfect target for any notification you want.

```js
const observer = new MutationObserver(ms => {
  ms.filter(m =>
    m.type === 'childList' &&
    m.removedNodes.length
  ).forEach(m =>
    ms.filter.call(
      m.removedNodes,
      n => n.nodeType === Node.ELEMENT_NODE
    ).forEach(n =>
      n.dispatchEvent(new Event('removed'))
    )
  )
});

// find a place to render
const render = hyperHTML.bind(document.body);

// parse first time
update(render, {text: 'Hello World'});

// now listen to eventual changes
// hint: nothing will happen in this example
observer.observe(document.body);

setTimeout(update, 500, render, {text: 'Hello to you!'});

function update(render, model) {
  render`<div> ${model.text} </div>`;
}
```
