### ISSUE TITLE
Give an id to wire instead of a type?

### ISSUE THREAD

**Issue by JSteunou** [WebReflection/hyperHTML#68]
What happens if I'm using the same data object for 2 differents `div`? I understand I can use `wire(obj, ':div')` new syntax, but if my 2 templates are divs, is that gonna be useful?

**Comment by WebReflection** [comment]
:div can be :1 and :2 ... it's an ID , nothing to do with the content

**Comment by JSteunou** [comment]
Hoooo ok, I though it as to be the same like in the readme / examples. Also I read through the code very quickly and so `type` along with html & svg so I though it was very tight.

Thank you for the enlightenment :pray:
