### ISSUE TITLE
TypeError undefined is not an object

### ISSUE THREAD

**Issue by davidmerrique** [WebReflection/hyperHTML#69]
I'm not sure what to make of this, since I can't replicate it on any device.

We use Bugsnag to report javascript errors on our site, and it's been reporting a TypeError here on [L787](https://github.com/WebReflection/hyperHTML/blob/bcbd430c999bb5401df42879bb235050b8cda957/hyperhtml.js#L787)

It seems to be happening in both Chrome & Safari, desktop & mobile.

Here's the raw error:

```
TypeError undefined is not an object (evaluating 'e[t[n++]][t[n]]') 
    webpack:///node_modules/hyperhtml/hyperhtml.js:793 
    webpack:///node_modules/hyperhtml/hyperhtml.js:883 createUpdates
    webpack:///node_modules/hyperhtml/hyperhtml.js:931 upgrade
    webpack:///node_modules/hyperhtml/hyperhtml.js:20 hyperHTML
```

`e[t[n++]][t[n]]` is `parentNode[path[i++]][path[i]]` minified.

Not sure what to do here as I can't replicate this, just wondering if you had any thoughts.

Thanks!

**Comment by joshgillies** [comment]
@davidmerrique Huh, that is weird... Would you be able to provide any additional info? eg. which version of hyperHTML are you using to produce these errors? Are you using viperHTML to render your templates server side before sending them to the client? Do you have specific versions of the browsers are are causing the above error?

**Comment by WebReflection** [comment]
Were you adopting the node?
Considering how paths are created and retrieved there are very few chances an error like that could happen. If you are manipulating nodes or attributes with other libraries though, bad things could happen. If you cannot provide any extra info there's not much I can do.

**Comment by davidmerrique** [comment]
@WebReflection @joshgillies 

I'm using the latest version - `0.15.5`. Not using viperHTML. Bugsnag is reporting the errors in Safari 8.x.x/9.x.x, Chrome 52/53.

I'm just doing something like this:

```javascript
import hyperHTML from 'hyperhtml';

function element() {
  const state = {
    contents: ''
  };

  return {
    setContent
  };

  function setContent(content) {
    state.contents = content;

    return el();
  }

  function el() {
    return hyperHTML.wire(state)`
      <div>${state.contents}</div>
    `;
  }
}

function innerElement() {
  return hyperHTML.wire()`
    <div>InnerEl</div>
  `;
}

const myElement = element().setContent(innerElement());

document.body.appendChild(myElement);
```

Is this allowed? Having the contents of that element be either a string or a wired node?

Thank you

**Comment by davidmerrique** [comment]
Ah, also another couple of questions:

Is this okay?

```javascript
const lang = {
  sentence: getText()
};

function getText() {
  return 'I am text';
}

hyperHTML.wire()`
  <p>${lang.sentence}</p>
`;
```

If other libraries can cause problems, how would one use something like Parsley for form validation?

```javascript
import $ from 'jquery';
import hyperHTML from 'hyperhtml';
import 'parsleyjs';

const form = hyperHTML.wire()`
  <form>
    <input type="text" required/>
    <button>Save</button>
  </form>
`;

document.body.appendChild(form);

$(form).parsley();
```

Thanks!

**Comment by WebReflection** [comment]
> Is this allowed? Having the contents of that element be either a string or a wired node?

that example works for me, no errors showed. you can use wires like that but only if you have a single element, otherwise wires are arrays and you cannot append arrays directly, you need to bind a context.

> also another couple of questions: Is this okay?

No if you want text because you need different chars around the interpolation.
```js
// vulnerable to HTML injection
hyperHTML.wire()`
  <p>${lang.sentence}</p>
`;

// sanitized text
hyperHTML.wire()`
  <p> ${lang.sentence} </p>
`;
```
Spaces are meaningless in HTML, use them when you want text and not html.

> If other libraries can cause problems, how would one use something like Parsley for form validation?

Your last example is abusing hyperHTML 'cause there's no interpolation at all. It's OK but I'm not sure how useful is that.

Anyway, that example would never have issues with anything so please probide a better example.

In any case, if the library you are using uses innerHTML or it manipulates the node or its attributes and you have those nodes or attributes mapped (interpolations) you might have problems but only you can test that stuff an d be sure it works.

**Comment by davidmerrique** [comment]
There seems to be a problem in iOS 8.1. 
Taking a look now, I'll let you know what I find.

**Comment by WebReflection** [comment]
again, if you want text **you need to put spaces around the interpolation** or instead you have injected HTML.

```js
const text = 'I am not okay';
hyperHTML.wire()`
  <div> ${text} </div>
`;
```
Does this produce the same result?

I have an iPad 5th gen with iOS 9.3 .... not sure how to test with 8 since the iPad 1 got stuck at iOS 5

I'm not sure there's a market share for iOS 8

**Comment by WebReflection** [comment]
I might know what's the problem ... it seems to affect webOS 2 too and probably iOS 5+ 'till iOS 9

It looks like the document fragment doesn't have a children property there ... how weird, I thought DOM4 would've patched that, it didn't

**Comment by davidmerrique** [comment]
Same result.

Looks like Safari 8 doesn't support `document.children`

**Comment by WebReflection** [comment]
it does, but it doesn't support `'children' in document.createDocumentFragment()`

give me few minutes

**Comment by davidmerrique** [comment]
In Chrome `document.children` is `[html]`, in Safari 8 it's `undefined`.

Thanks!

**Comment by WebReflection** [comment]
can you please double check that `'children' in document.createDocumentFragment()` is also false in Safari 8 ?

**Comment by davidmerrique** [comment]
Correct

**Comment by WebReflection** [comment]
the current `0.15.6` should work on iOS 8 too

**Comment by davidmerrique** [comment]
Works perfectly, thanks so much.
