### ISSUE TITLE
[EDGE] Unable to get property 'apply' of undefined or null reference

### ISSUE THREAD

**Issue by moebiusmania** [WebReflection/hyperHTML#70]
hi, I'm building some elements that hopefully will go live on production after the summer break... and this brought me to test them on Microsoft Edge, meh 😕.

In all browsers everything is going fine, on Edge I'm facing the title message, for debugging purpose I have "simplified" the code involved like this:

```javascript
<div >${this.state.links.applications.map(item => {
  return hyperHTML.wire(item)`<p>test</p>`
})}</div>
```

but I'm still getting that message... inspecting the page, this is the code that is being generated:

```html
<div><!--_hyper_html: -172961272;--></div>
```

Any insight/suggestion will be appreciated 😃

**Comment by WebReflection** [comment]
Hi, I've just tested this on Edge and it works just fine:
```js
this.onload = () => {
  const applications = [{name: 'first'}, {name: 'second'}];
  hyperHTML.bind(document.body)`<div >${
    applications.map(item => hyperHTML.wire(item)`<p> ${item.name} </p>`)
  }</div>`;
};
```

**Comment by WebReflection** [comment]
Hey @moebiusmania I'm not sure it fixed your issue but I've discovered myself Edge was having problems with virtual nodes due bugs on comments nodes.

Can you please try `v0.15.7` and let me know if everything is fine now?

Thank you

**Comment by aMarCruz** [comment]
@moebiusmania ....and make sure your page has an `<!DOCTYPE html>` directive.
hyperHTML does not work on IE compatibiliy mode.

**Comment by moebiusmania** [comment]
@WebReflection sorry, I've forgot an important information, that code is inside a V1 Web Component (without Shadow DOM). Unfortunately it seems that `v0.15.7` is not resolving this particular issue, but I thank you for the effort you have put on release a fix so quickly!

@aMarCruz no compatibility mode obviously 😉

**Comment by moebiusmania** [comment]
sorry clicked close unintentionally 😸

**Comment by WebReflection** [comment]
I need the smallest piece of code able to reproduce an error otherwise I can't fix much.

Moreover, Edge doesn't ship with CustomElements V1 or does it ?

So maybe other parts of the transpilers or polyfills are involved?

Can you show me a page that doesn't work on Edge?

Not sure how to move forward otherwise, thank you.

**Comment by moebiusmania** [comment]
@WebReflection it's Web Component v1 via the Google polyfills , so it's Shady DOM with Edge. I'll try to put on a little repo with a minimum code that reproduce the issue in the next hours. Thanks

**Comment by davidmerrique** [comment]
@moebiusmania Are you using [polyfill.io](https://polyfill.io/v2/docs/)?

If so, I just ran into this error. 

It's caused by [this polyfill](https://github.com/Financial-Times/polyfill-service/blob/642a6089d50f998e24356fad99e69d28ca6c734a/polyfills/Element/prototype/append/polyfill.js) that polyfills `Element.prototype.append `/`Document.prototype.append `.

And this line [L757](https://github.com/WebReflection/hyperHTML/blob/4cc34e8b7eefe25438bd9ba7f15d51153c5671e9/hyperhtml.js#L757)

**Comment by WebReflection** [comment]
You are right @davidmerrique , that polyfill is completely broken.

I've filed a bug, you should avoid their stuff and use [dom4](https://github.com/WebReflection/dom4) instead or include `hyperHTML` **before** any other wannabe polyfill (yes, including Custom Elements ... just include hyperHTML before everything else and it'll work)

**Comment by WebReflection** [comment]
@moebiusmania and @davidmerrique please try `v0.15.8` and let me know if your problems are gone.

I've changed `hyperHTML` in a way that should survive after partial/broken polyfills too.

Thank you!

**Comment by davidmerrique** [comment]
@WebReflection Fixed for me! Thank you!

**Comment by WebReflection** [comment]
@moebiusmania any progress on that failing example?

**Comment by WebReflection** [comment]
I am close ... to close this ... if nothing happens today.

**Comment by moebiusmania** [comment]
@WebReflection sorry, busy days! I'm giving a try with `v0.15.8` this afternoon

**Comment by moebiusmania** [comment]
@WebReflection man it's working! you're awesome! (noticed its already `v0.15.10`)

sorry for the example repo, had some problem since it was tied to some internals-only-company-APIs 😕 .

I'm planning to "give you something back" by talking about HyperHTML (and few others of your repos) in some meetups and conferences around Milan.

thanks again!

**Comment by WebReflection** [comment]
Thanks for double checking.

The patch number is changing quickly but it's actually for npmjs reasons (the README wasn't OK)

I mean ....the library should be very stable now 🎉
