### ISSUE TITLE
hyperhtml.js:909 Uncaught TypeError: template.join is not a function

### ISSUE THREAD

**Issue by lastmjs** [WebReflection/hyperHTML#76]
I'm trying to get a simple example working inside of a custom element:

```
connectedCallback() {
    this.innerHTML = `<div id="hyper-test"></div>`;
    hyperHTML(document.getElementById('hyper-test'));
}
```

It throws:

```
hyperhtml.js:909 Uncaught TypeError: template.join is not a function
```

**Comment by lastmjs** [comment]
The `template` variable that is supposed to have the join function is indeed my `<div id="hyper-test"></div>`.

**Comment by lastmjs** [comment]
Could I get some help on this?

**Comment by WebReflection** [comment]
This is not a `hyperHTML` bug unless:

  * you provide a whole example I can understand
  * you have read [all the examples](https://viperhtml.js.org/hyperhtml/examples/#!fw=Polymer&example=custom-element) related to custom elements

**Comment by WebReflection** [comment]
also ... this ?
```js
hyperHTML(document.getElementById('hyper-test'));
```
that is **not** how you use `hyperHTML`.

[GETTING_STARTED](https://github.com/WebReflection/hyperHTML/blob/master/GETTING_STARTED.md) here

[DEEP_DIVE](https://github.com/WebReflection/hyperHTML/blob/master/DEEPDIVE.md) there.

You need to **bind** a context or nothing happens.

You need to understand the basic API before you can use it.

Now I see why you complained about the module style without ever having even used `hyperHTML`.

I hope you'll find those links a good getting-started, please stop filing bugs unless you have done basic homeworks like you have to do for any library or framework out there, thank you!

**Comment by lastmjs** [comment]
I'll simplify it:

```
<!DOCTYPE html>

<html>
    <head>
        <script src="node_modules/hyperhtml/hyperhtml.js"></script>
    </head>

    <body>
        <div id="hyper-test"></div>

        <script>
            hyperHTML(document.getElementById('hyper-test'));
        </script>
    </body>
</html>
```

This throws:
```
Uncaught TypeError: template.join is not a function
```

**Comment by lastmjs** [comment]
Sorry, I just read what you posted before this, I'll look into that.

**Comment by WebReflection** [comment]
Yeah, and it will throw forever until you read the most basic documentation about `hyperHTML`

**Comment by lastmjs** [comment]
Shoot, I just missed the `bind` function. It's working now, thanks! Sorry about that.

**Comment by WebReflection** [comment]
an empty bind means nothing anyway ... **keep reading**

**Comment by WebReflection** [comment]
the following would be already an improvement

```js
connectedCallback() {
  hyperHTML.bind(this)`
  <div id="hyper-test"></div>`;
}
```

but if you use `hyperHTML` as plain substitute of `innerHTML` you are not using its potentials at all.

The documentation is what I'm working on and what is my [Patreon](https://www.patreon.com/webreflection) about.

It's not perfect now, but there are tons of examples and documents already.

**Comment by lastmjs** [comment]
Don't worry, I have big plans for `hyperHTML`. I'm hoping to replace Polymer's data binding completely if possible, and rid myself of that dependency.

**Comment by WebReflection** [comment]
with even less documentation a this stage, [this class](https://github.com/WebReflection/hyperHTML-Element) helped me creating all Polymer counter examples.

Happy to give hints in DM, if necessary.
