### ISSUE TITLE
hyperHTML.adopt() inconsistent behaviour

### ISSUE THREAD

**Issue by joshgillies** [WebReflection/hyperHTML#82]
Have been playing with the `hyperHTML.adopt()` API recently, and I'm seeing some odd behaviour.

Given the following:

```html
<body>
  <div id="root">
    <h1>Hello, world!</h1><h2>disconnected</h2><h3>It is ???.</h3>
  </div>
  <script src="https://unpkg.com/hyperhtml@0.17.4"></script>
  <script>
    var connected = hyperHTML.wire()`<h2>connected</h2>`
    function tick(render) {
      render`
        <div id="root">
          <h1>Hello, world!</h1>${[
            connected
          ]}<h3>It is ${new Date().toLocaleTimeString()}.</h3>
        </div>
      `
    }
    setInterval(tick, 1000,
      hyperHTML.adopt(document.body)
    )
  </script>
</body>
```

The `h3` node doesn't seem to get adopted - but if I wrap the `h2` node in a `div` it then works as expected.

**Comment by WebReflection** [comment]
I'm in the middle of a huge refactoring and `.adopt`, as experimental and fragile as it inevitably is, might be working better (or worse) now.

I'll keep this open for an after V1 release. Meanwhile, just bind the body instead, it's better in any case for highly dynamic content.

`adopt` main use case is for **forms**, not regular layout without inputs. It's a mechanism to pick up content without losing focus or cursor position.

It's a killer for progressive enhancement after rendering with the *exact same template* nodes generated through `viperHTML`.

For every other case, just bind the content and you'll be better off with less surprises :wink:

**Comment by joshgillies** [comment]
Thanks for the input, and I feel the same. Will close this off, and revisit if there's a real need into the future. Thanks!
