### ISSUE TITLE
A bit unclear on conditional wires

### ISSUE THREAD

**Issue by davidmerrique** [WebReflection/hyperHTML#88]
Either I'm confused or this might be a bug. 

I'm trying to toggle a wired element based on a condition, but it only works properly if I write it a certain way.

```javascript
// This doesn't work
`<span>${condition ? element() : ''}</span>`
// This works
`<span>${[condition ? element() : '']}</span>`
```

Here's my CodePen https://codepen.io/davidmerrique/pen/OjEZKx?editors=0010

Thank you

**Comment by WebReflection** [comment]
Good catch, thank you! (fixed in v1.2.1)
