### ISSUE TITLE
moar magic ?

### ISSUE THREAD

**Issue by WebReflection** [WebReflection/hyperHTML#90]
I've played a little bit with an export called just `hyper` with the following behaviors:

  * `hyper` as tag, same as `hyper()` for a new wire usable as tag
  * `hyper(domNode)` use `domNode` to render content. Alias for `hyperHTML.bind(domNode)`
  * `hyper(object[, typeOrID])` as alias for `hyperHTML.wire(object[, typeOrID])`

The signature allows to play with a single entry point in various ways:
```js
hyper(document.body)`
${hyper`<h1>Hello ${'hyper'} !</h1>`}
<ul>
  ${[{name: 'a'}, {name: 'b'}].map((item, i) => hyper(item)
  `<li data-index=${i}>${item.name}</li>`)}
</ul>`;
```

My thoughts are between "_ok, cool!_" and "_maybe it's going to be even more confusing_", promoting as side effect bad practices.

But after all, not every website needs 60FPS updates ... so what are your thoughts ?

**Comment by WebReflection** [comment]
P.S. the branch is here: https://github.com/WebReflection/hyperHTML/tree/magic

**Comment by bigopon** [comment]
Why does it affect fps, isn't calling just simple switch with 3 - 5 cases inside update ?

It looks more dev friendly to me, only 1 API to rule it all.

**Comment by WebReflection** [comment]
In that basic example, every new call to function that renders the H1 as such:

```js
hyper`<h1>Hello ${'hyper'} !</h1>`
```
will inevitably create a new H1 element each time.

What I meant is that this is not really the best way, performance wise, but it's surely also not the end of the world if you don't need to update that  body at 60FPS.

> It looks more dev friendly to me, only 1 API to rule it all.

My only concern is the inability to wire a document node, if necessary, but that's also probably a never so useful use-case.

Thanks for giving your  thoughts.

**Comment by bigopon** [comment]
Oh i see that's why the mention of promoting side effect / bad practices. It would be nice if you could use string as an indicator to avoid creating new element.

**Comment by WebReflection** [comment]
Sorry, what?

**Comment by WebReflection** [comment]
## Introducing a user friendly `hyper(HTML)` entry point

  * `` hyper`<p>runtime</p>` `` to create one-off DOM content
  * `` hyper(node)`<p>bound content</p>` `` to bind `node` as hyperHTML context
  * `` hyper(obj, typeOrId)`<li>wire</li>` `` as alias for hyperHTML.wire

The new API shortcut is now the default export.
It exposes exact same API already available before.

- - -

## Introducing an unserialized/rich `data` attribute.

Apparently other frameworks are capable of sending rich data
to either custom elements or, more generically, DOM nodes.

This version flags `data` attribute as special case,
sending the value as it is instead of needing serialization/stringification.

This is needed to better score on modern benchmarks such:
https://github.com/webcomponents/custom-elements-everywhere
