### ISSUE TITLE
Who's using hyper.adopt(...) ?

### ISSUE THREAD

**Issue by WebReflection** [WebReflection/hyperHTML#96]
After v1.6 and all the latest improvements done to work well with Custom Elements and define non Custom Elements components, I think I can declare V1 **frozen**.

However, I would like to do an ultimate clean-up, splitting the library in two versions (built at runtime and both available via unpkg CDN):

  * minimal version without adopt capabilitites
  * a fully refactored, non experimental, adopt logic, still integrated in the private scope

My idea is that being experimental, adopt is not something truly necessary, specially if you don't use viperHTML, which is basically the only reason you would adopt some content.

Does anyone has valid reasons for not removing adopt from the default core library?

For those actually using it, v1.7 will provide an `adopt.js` file too (and minified version)

**Comment by albertosantini** [comment]
It seems I don't use it.

Anyway, generally speaking, different builds is confusing or, at least, compel the developer to a choice.
Choosing a particular flavor from many is a "cognitive load". :)

**Comment by WebReflection** [comment]
I have two options here:

  1. create two versions so that hyperHTML as is stays under 4K (branch light is already 3.9)
  2. refactor properly the adopt bit and make it work with 100% reliability within the core

The second option will inevitably see the library reach up to 5K.

Now, that's not the end of the world, isn't it? But bloating 1K for something never used in most of the cases did't feel too right, hence my question.

Today, I've also seen that developers consider lightweight Vuew.js which is around 60KB ... so maybe, I just close this issue and move on without bothering much.

**Comment by albertosantini** [comment]
I vote #2. 

Then, finally, reconsider the topic in 2.x.
